dive                  = 33
force_jump            = 34

 ["sw_force_jump2", acf_displace_position|acf_enforce_lowerbody, amf_priority_jump|amf_keep,
   [0.04, "force_jump", 0, 1, arf_blend_in_10, 0, (0,0.5,1.1), 0],
 ],
 ["sw_force_jump2_end", acf_displace_position|acf_enforce_lowerbody, amf_priority_jump|amf_keep,
   [0.04, "jetpack_end", 0, 1, arf_blend_in_10, 0, (0,0.5,0.1), 0],
 ],

   ("cf_agent_force_jump",
    [
     (store_script_param, ":agent_force_jump",1),
     (agent_get_troop_id, ":troop_no", ":agent_force_jump"),
     (store_character_level,":ch_bonus",":troop_no"),
     
     (agent_get_position, pos1, ":agent_force_jump"),   
     (val_mul,":ch_bonus",500),
     
     (assign,":victim",-1),
     (try_for_agents,":agent"),
       (agent_is_alive,":agent"),
       (agent_is_human,":agent"),
       (eq,":victim",-1),
       
       (this_or_next|agent_is_ally,":agent_force_jump"),
       (agent_is_ally,":agent"),
       (this_or_next|neg|agent_is_ally,":agent"),
       (neg|agent_is_ally,":agent_force_jump"),
       
       (neg|agent_slot_eq, ":agent", slot_agent_has_been_special_ability, shadowstep), 
       
       (agent_get_horse, ":horse_agent", ":agent"),
       (lt, ":horse_agent", 0),
       (agent_get_position, pos2, ":agent"),
       (get_distance_between_positions,":distance",pos2,pos1),
       (le,":distance",":ch_bonus"),
       (call_script, "script_agent_get_num_companion_nearby", ":agent", 500),
       (assign, ":num_enemies", reg0),
       (le, ":num_enemies", 5),
       (assign,":victim",":agent"),
     (try_end),
     (get_player_agent_no,":player"),
     (this_or_next|eq,":agent_force_jump",":player"),
     (ge,":victim",0),
     
     (agent_set_animation, ":agent_force_jump", "anim_sw_force_jump2", 0),
]),  

        (else_try),
          (eq,":special",force_jump),
          (assign, ":cost_stamina", 30),
          (ge, ":stamina", ":cost_stamina"),
          (agent_get_team, ":agent_team", ":agent_no"),
          (agent_get_division, ":agent_division", ":agent_no"),
          (team_get_movement_order, ":movement_order", ":agent_team", ":agent_division"),
          (neg|eq,":movement_order",mordr_hold),
          (neg|eq,":movement_order",mordr_follow),
          (neg|eq,":movement_order",mordr_stand_ground),
          (neg|eq,":movement_order",mordr_fall_back),
          (neg|eq,":movement_order",mordr_hold_fire),
          (neg|eq,":movement_order",mordr_fire_at_will),
          (neg|eq,":movement_order",mordr_retreat),
          (neg|eq,":movement_order",mordr_fire_at_my_command),
          (neg|eq,":movement_order",mordr_all_fire_now),
          (neg|eq,":movement_order",mordr_left_fire_now),
          (neg|eq,":movement_order",mordr_middle_fire_now),
          (neg|eq,":movement_order",mordr_right_fire_now),
          (agent_get_horse, ":horse_agent", ":agent_no"),
          (lt, ":horse_agent", 0),
          (try_begin),
            (val_sub, ":stamina", ":cost_stamina"),
            (agent_set_slot, ":agent_no", slot_agent_stamina, ":stamina"),
            (call_script, "script_cf_agent_force_jump", ":agent_no"),
            (val_sub, ":stamina", ":cost_stamina"),
            (agent_set_slot, ":agent_no", slot_agent_special_ability_counter, 10),
            (agent_set_slot, ":agent_no", slot_agent_stamina, ":stamina"),
          (try_end),
          (store_random_in_range, ":ran", 5, 16),
          (agent_set_slot, ":agent_no", slot_agent_special_ability_cooldown, ":ran"),

        (try_begin),
          (eq,":special",force_jump),
          (agent_get_slot, ":time", ":agent_no", slot_agent_special_ability_counter),
          (le, ":time", 0),
          (agent_get_animation, ":anim", ":agent_no"),
          (eq, ":anim", "anim_sw_force_jump2"),
          (agent_set_animation, ":agent_no", "anim_sw_force_jump2_end", 0),
        (try_end),
          
      (try_begin),
        (eq,":special", force_jump),
        (agent_get_slot, ":time", ":agent_no", slot_agent_special_ability_counter),
        (le, ":time", 0),
        (agent_get_animation, ":anim", ":agent_no"),
        (eq, ":anim", "anim_sw_force_jump2"),
        (agent_set_animation, ":agent_no", "anim_sw_force_jump2_end", 0),
      (try_end),        

      (try_begin),
        (this_or_next|troop_slot_eq, ":troop_no", slot_troop_special_ability, force_jump), 
        (troop_slot_eq, ":troop_no", slot_troop_special_ability, dive),
        (agent_get_slot, ":time", ":agent_no", slot_agent_special_ability_counter),
        (agent_get_horse, ":horse_agent", ":agent_no"),
        (try_begin),
          (this_or_next|is_between,":time",5,10),
          (is_between,":time",15,20),
          (ge, ":horse_agent", 0),
          (agent_get_animation, ":anim", ":horse_agent"),
          (neq, ":anim", "anim_horse_jump2"),
          (agent_set_animation, ":horse_agent", "anim_horse_jump2", 0),
        (else_try),
          (this_or_next|is_between,":time",5,10),
          (is_between,":time",15,20),
          (lt, ":horse_agent", 0),
          (agent_get_animation, ":anim", ":agent_no"),
          (neq, ":anim", "anim_sw_force_jump2"),
          (agent_set_animation, ":agent_no", "anim_sw_force_jump2", 0),
        (else_try),
          (gt,":time",0),
          (ge, ":horse_agent", 0),
          (agent_set_animation, ":horse_agent", "anim_horse_jump2", 0),
        (else_try),
          (gt,":time",0),
          (lt, ":horse_agent", 0),
          (agent_set_animation, ":agent_no", "anim_sw_force_jump2", 0),
        (else_try),
          (le, ":time", 0),
          (ge, ":horse_agent", 0),
          #(agent_get_animation, ":anim", ":horse_agent"),
          #(eq, ":anim", "anim_horse_jump2"),
          (agent_set_animation, ":horse_agent", "anim_horse_jump_end2", 0),
        (else_try),
          (le, ":time", 0),
          (lt, ":horse_agent", 0),
          #(agent_get_animation, ":anim", ":agent_no"),
          #(eq, ":anim", "anim_sw_force_jump2"),
          (agent_set_animation, ":agent_no", "anim_sw_force_jump2_end", 0),
        (try_end),        
      (try_end),        

      (try_begin),
        (eq,":special", force_jump),
        (agent_get_slot, ":time", ":agent_no", slot_agent_special_ability_counter),
        (agent_get_animation, ":anim", ":agent_no"),
        (gt,":time",0),
        (this_or_next|is_between,":time",5,10),
        (this_or_next|is_between,":time",15,20),
        (neq, ":anim", "anim_sw_force_jump2"),
        (agent_set_animation, ":agent_no", "anim_sw_force_jump2", 0),
      (else_try),
        (le, ":time", 0),
        (agent_get_animation, ":anim", ":agent_no"),
        (eq, ":anim", "anim_sw_force_jump2"),
        (agent_set_animation, ":agent_no", "anim_sw_force_jump2_end", 0),
      (try_end),        
      (try_begin),
        (eq,":special", dive),
        (agent_get_slot, ":time", ":agent_no", slot_agent_special_ability_counter),
        (agent_get_horse, ":horse_agent", ":agent_no"),
        (agent_get_animation, ":anim", ":agent_no"),
        (gt, ":horse_agent", 0),
        (gt,":time",0),
        (this_or_next|is_between,":time",5,10),
        (this_or_next|is_between,":time",15,20),
        (neq, ":anim", "anim_horse_jump2"),
        (agent_set_animation, ":agent_no", "anim_horse_jump2", 0),
      (else_try),
        (le, ":time", 0),
        (agent_get_horse, ":horse_agent", ":agent_no"),
        (gt, ":horse_agent", 0),
        (agent_get_animation, ":anim", ":horse_agent"),
        (eq, ":anim", "anim_horse_jump2"),
        (agent_set_animation, ":agent_no", "anim_horse_jump_end", 0),
        (call_script, "script_cf_agent_dive", ":agent_no"),
      (try_end),        
