from header_map_icons import *
from module_constants import *
from header_operations import *
from header_triggers import *
from ID_sounds import *

####################################################################################################################
#  Each map icon record contains the following fields:
#  1) Map icon id: used for referencing map icons in other files.
#     The prefix icon_ is automatically added before each map icon id.
#  2) Map icon flags. See header_map icons.py for a list of available flags
#  3) Mesh name.
#  4) Scale. 
#  5) Sound.
#  6) Offset x position for the flag icon.
#  7) Offset y position for the flag icon.
#  8) Offset z position for the flag icon.
####################################################################################################################

banner_scale = 0.3
avatar_scale = 0.15
huge_scale = 0.45

map_icons = [
  ("player",0,"player", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("player_horseman",0,"player_horseman", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  #new
  ("player_2",0,"player_huge", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("player_horseman_2",0,"player_horseman_huge", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  #new
  ("gray_knight",0,"knight_a", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  ("vaegir_knight",0,"knight_b", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  ("flagbearer_a",0,"flagbearer_a", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  ("flagbearer_b",0,"flagbearer_b", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  #new
  ("flagbearer_2",0,"flagbearer", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  #new
  ("peasant",0,"peasant_a", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  ("khergit",0,"khergit_horseman", avatar_scale,snd_gallop, 0.15, 0.173, 0),
  ("khergit_horseman_b",0,"khergit_horseman_b", avatar_scale,snd_gallop, 0.15, 0.173, 0),
  ("axeman",0,"bandit_a", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  ("archer",0,"human_archer", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  #new
  ("brigand",0,"brigand", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  
  ("dwarf",0,"dwarf", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("lorien_elf_a",0,"lorien_elf_a", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("lorien_elf_b",0,"lorien_elf_b", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("mirkwood_elf",0,"mirkwood_elf", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("dunlander",0,"dunlander", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0), # beorn (**ordering exception**-- will use generic x3) , TODO: better icon needed
  ("dunland_captain",0,"dunland_captain", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  ("easterling_horseman",0,"easterling_horseman", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  ("cataphract",0,"cataphract", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  ("umbar_corsair",0,"umbar_corsair", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("demons",0,"demons", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("skeletons",0,"skeletons", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("skeleton_archer",0,"skeleton_archer", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("single_unholy_knight",0,"single_unholy_knight", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("drow_fighter",0,"drow_fighter", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("shadows",0,"shadows", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("orc_tribal",0,"orc_tribal", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  ("orc",0,"orc", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("uruk",0,"uruk", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("wargrider_run",0,"wargrider_run", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  
  
  
  #new

  #new
  ("unholy_knights",0,"unholy_knights", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("skeletons_x3",0,"skeletons_x3", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("undead_army",0,"undead_army", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),

  ("drow_army",0,"drow_army", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("demon_x3",0,"demons_x3", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("generic_knight_x3",0,"generic_knight_x3", avatar_scale, snd_gallop, 0.15, 0.173, 0), # dale: TODO: better icon needed
  ("easterling_horseman_x3",0,"easterling_horseman_x3", avatar_scale, snd_gallop, 0.15, 0.173, 0), # rhur  TODO: better icon needed
  ("dunlander_x3",0,"dunlander_x3", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("cataphract_x3",0,"cataphract_x3", avatar_scale, snd_gallop, 0.15, 0.173, 0), # easeterlings ( khand)
  ("umbar_corsair_x3",0,"umbar_corsair_x3", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),

  ("lorien_elf_b_x3",0,"lorien_elf_b_x3", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("mirkwood_elf_x3",0,"mirkwood_elf_x3", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("dwarf_x3",0,"dwarf_x3", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),

  ("orc_tribal_x4",0,"orc_tribal_x4", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0), # moria
  ("orc_x4",0,"orc_x4", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),  # guldur 
  ("uruk_x4",0,"uruk_x4", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),  # moria
  ("wargrider_walk_x4",0,"wargrider_walk_x4", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  ("wild_troll",0,"wild_troll", avatar_scale, snd_footstep_grass, 0.15, 0.173, 0),
  #new
  ("huge_gray_knight",0,"knight_x3", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  ("huge_peasant_1",0,"knight_axeman_x2_peasant_x2", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  ("huge_peasant_2",0,"knight_peasant_x4", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  ("huge_peasant_3",0,"peasant_x4", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  ("huge_khergit",0,"khergit_horseman_x3", avatar_scale,snd_gallop, 0.15, 0.173, 0),
  ("huge_axeman",0,"bandit_a_x3", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  ("huge_archer",0,"human_archer_x3", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  ("huge_flagbearer",0,"knight_axeman_x2", avatar_scale, snd_gallop, 0.15, 0.173, 0),
  #new

  ("woman",0,"woman_a", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  ("woman_b",0,"woman_b", avatar_scale,snd_footstep_grass, 0.15, 0.173, 0),
  ("town",mcn_no_shadow,"map_town_a", 0.35,0),
  ("town_steppe",mcn_no_shadow,"map_town_steppe_a", 0.35,0),
  ("town_desert",mcn_no_shadow,"map_town_desert_a", 0.35,0),
  ("village_a",mcn_no_shadow,"map_village_a", 0.45, 0),
  ("village_b",mcn_no_shadow,"map_village_b", 0.45, 0),
  ("village_c",mcn_no_shadow,"map_village_c", 0.45, 0),
  ("village_burnt_a",mcn_no_shadow,"map_village_burnt_a", 0.45, 0),
  ("village_deserted_a",mcn_no_shadow,"map_village_deserted_a", 0.45, 0),
  ("village_burnt_b",mcn_no_shadow,"map_village_burnt_b", 0.45, 0),
  ("village_deserted_b",mcn_no_shadow,"map_village_deserted_b", 0.45, 0),
  ("village_burnt_c",mcn_no_shadow,"map_village_burnt_c", 0.45, 0),
  ("village_deserted_c",mcn_no_shadow,"map_village_deserted_c", 0.45, 0),
  ("village_snow_a",mcn_no_shadow,"map_village_snow_a", 0.45, 0),
  ("village_snow_burnt_a",mcn_no_shadow,"map_village_snow_burnt_a", 0.45, 0),
  ("village_snow_deserted_a",mcn_no_shadow,"map_village_snow_deserted_a", 0.45, 0),


  ("camp",mcn_no_shadow,"camp_tent", 0.13, 0),
  ("ship",mcn_no_shadow,"boat_sail_on", 0.23, snd_footstep_grass, 0.0, 0.05, 0),
  ("ship_on_land",mcn_no_shadow,"boat_sail_off", 0.23, 0),

  ("castle_a",mcn_no_shadow,"map_castle_a", 0.35,0),
  ("castle_b",mcn_no_shadow,"map_castle_b", 0.35,0),
  ("castle_c",mcn_no_shadow,"map_castle_c", 0.35,0),
  ("castle_d",mcn_no_shadow,"map_castle_d", 0.35,0),
  ("town_snow",mcn_no_shadow,"map_town_snow_a", 0.35,0),


  ("castle_snow_a",mcn_no_shadow,"map_castle_snow_a", 0.35,0),
  ("castle_snow_b",mcn_no_shadow,"map_castle_snow_b", 0.35,0),
  

  ("castle_x_1",mcn_no_shadow,"map_castle_x_1", 0.35,0),
  ("castle_x_2",mcn_no_shadow,"map_castle_x_2", 0.35,0),
  ("castle_x_3",mcn_no_shadow,"map_castle_x_3", 0.35,0),
  ("castle_x_4",mcn_no_shadow,"map_castle_x_4", 0.35,0),
  ("castle_x_5",mcn_no_shadow,"map_castle_x_5", 0.35,0),
  ("castle_x_6",mcn_no_shadow,"map_castle_x_6", 0.35,0),
  ("castle_x_7",mcn_no_shadow,"map_castle_x_7", 0.35,0),
  ("castle_x_8",mcn_no_shadow,"map_castle_x_8", 0.35,0),
  ("castle_x_9",mcn_no_shadow,"map_castle_x_9", 0.35,0),
  ("castle_x_10",mcn_no_shadow,"map_castle_x_10", 0.35,0),
  ("castle_x_11",mcn_no_shadow,"map_castle_x_11", 0.35,0),
  ("castle_x_12",mcn_no_shadow,"map_castle_x_12", 0.35,0),
  ("castle_x_13",mcn_no_shadow,"map_castle_x_13", 0.35,0),
  ("castle_x_14",mcn_no_shadow,"map_castle_x_14", 0.35,0),
  ("castle_x_15",mcn_no_shadow,"map_castle_x_15", 0.35,0),
  ("castle_x_16",mcn_no_shadow,"map_castle_x_16", 0.35,0),
  ("castle_x_17",mcn_no_shadow,"map_castle_x_17", 0.35,0),
  ("castle_x_18",mcn_no_shadow,"map_castle_x_18", 0.35,0),
  ("castle_x_19",mcn_no_shadow,"map_castle_x_19", 0.35,0),
  ("castle_x_20",mcn_no_shadow,"map_castle_x_20", 0.35,0),
  ("castle_x_21",mcn_no_shadow,"map_castle_x_21", 0.35,0),
  ("castle_x_22",mcn_no_shadow,"map_castle_x_22", 0.35,0),
  ("castle_x_23",mcn_no_shadow,"map_castle_x_23", 0.35,0),
  ("castle_y_1",mcn_no_shadow,"map_castle_y_1", 0.35,0),
  ("castle_y_2",mcn_no_shadow,"map_castle_y_2", 0.35,0),
  ("castle_y_3",mcn_no_shadow,"map_castle_y_3", 0.35,0),
  ("castle_y_4",mcn_no_shadow,"map_castle_y_4", 0.35,0),
  ("castle_y_5",mcn_no_shadow,"map_castle_y_5", 0.35,0),
  ("castle_desert_1",mcn_no_shadow,"map_castle_desert_1", 0.35,0),
  ("castle_desert_2",mcn_no_shadow,"map_castle_desert_2", 0.35,0),
  ("castle_desert_3",mcn_no_shadow,"map_castle_desert_3", 0.35,0),
  ("castle_desert_4",mcn_no_shadow,"map_castle_desert_4", 0.35,0),
  ("castle_desert_5",mcn_no_shadow,"map_castle_desert_5", 0.35,0),
  ("castle_desert_6",mcn_no_shadow,"map_castle_desert_6", 0.35,0),
  ("castle_desert_7",mcn_no_shadow,"map_castle_desert_7", 0.35,0),
  ("castle_desert_8",mcn_no_shadow,"map_castle_desert_8", 0.35,0),
  ("castle_desert_9",mcn_no_shadow,"map_castle_desert_9", 0.35,0),
  ("castle_desert_10",mcn_no_shadow,"map_castle_desert_10", 0.35,0),
  ("castle_desert_11",mcn_no_shadow,"map_castle_desert_11", 0.35,0), 
  ("castle_wood_1",mcn_no_shadow,"map_castle_wood_1", 0.35,0),
  ("castle_wood_2",mcn_no_shadow,"map_castle_wood_2", 0.35,0),
  ("castle_wood_3",mcn_no_shadow,"map_castle_wood_3", 0.35,0),
  ("castle_wood_4",mcn_no_shadow,"map_castle_wood_4", 0.35,0),
  ("castle_wood_5",mcn_no_shadow,"map_castle_wood_5", 0.35,0),
  
  ("castle_hillfort",mcn_no_shadow,"map_castle_hillfort", 0.35,0),

  ("town_volencia",mcn_no_shadow,"map_town_volencia", 0.6,0), 
  ("town_vaegir_khudan",mcn_no_shadow,"map_town_vaegir_khudan", 0.6,0), 
  ("city_sarranid",mcn_no_shadow,"map_city_sarranid", 0.6,0), 
  ("city_rhodok",mcn_no_shadow,"map_city_rhodok", 0.6,0), 
  ("city_vaegir",mcn_no_shadow,"map_city_vaegir", 0.6,0), 
  ("city_swadia",mcn_no_shadow,"map_city_swadia", 0.6,0), 
  ("colony_fortified_a",mcn_no_shadow,"map_colony_fortified_a", 0.6,0), 
  ("colony_fortified_b",mcn_no_shadow,"map_colony_fortified_b", 0.6,0), 
  ("colony_fortified_c",mcn_no_shadow,"map_colony_fortified_c", 0.6,0), 
  ("town_normal",mcn_no_shadow,"map_town_normal", 0.6,0), 
  ("town_normal_2",mcn_no_shadow,"map_town_normal_2", 0.6,0), 

  ("town_10",mcn_no_shadow,"town_10", 0.6,0), 
  ("town_14",mcn_no_shadow,"town_14", 0.6,0), 
  ("town_19",mcn_no_shadow,"town_19", 0.6,0), 
  ("town_20",mcn_no_shadow,"town_20", 0.6,0), 
  ("town_22",mcn_no_shadow,"town_22", 0.6,0), 
  ("town_17",mcn_no_shadow,"town_17", 0.6,0), 
  ("town_15",mcn_no_shadow,"town_15", 0.6,0), 
  ("town_5",mcn_no_shadow,"town_5", 0.6,0), 
  ("town_6",mcn_no_shadow,"town_6", 0.6,0), 
  
  ("drachenburg",mcn_no_shadow,"map_drachenburg", 0.4,0), 
  ("viking_snow_town_port",mcn_no_shadow,"snow_map_tradeport", 1, 0), #ciudad con puerto chief Adorno
  ("viking_town_port",mcn_no_shadow,"map_tradeport", 1, 0), #ciudad con puerto chief Adorno
  ("viking_town_walled",mcn_no_shadow,"wall_town_icon", 1, 0), #con muro dentro hall y casas
  ("viking_fort1",mcn_no_shadow,"map_vikingcastle", 1, 0), #cambiado para capitales chief Adorno  
  ("viking_fort2",mcn_no_shadow,"hillfort_icon", 1,0), #dos murallas fuerte en colina Adorno    
  ("monastery",mcn_no_shadow,"monastery", 1,0), #icono monastery chief, para lugares de culto y ruinas

  ("sacred_forest",mcn_no_shadow,"sacred_forest", 1.2,0), #icono sacred forest chief, para templos paganos
  ("cave_2",mcn_no_shadow,"cave", 1.2,0), #
  ("camp_2",mcn_no_shadow,"camp_2", 1.2,0), #
  ("map_castle_nord",mcn_no_shadow,"map_castle_nord", 1.2,0), #



  ("map_temple",mcn_no_shadow,"map_calrad_temple_b", 0.45,0),
  
  ("mule",0,"icon_mule", 0.2,snd_footstep_grass, 0.15, 0.173, 0),
  ("cattle",0,"icon_cow", 0.2,snd_footstep_grass, 0.15, 0.173, 0),
  ("training_ground",mcn_no_shadow,"training", 0.35,0),

  ("bridge_a",mcn_no_shadow,"troll_bridge", 1.27,0),
  ("bridge_b",mcn_no_shadow,"map_river_bridge_b", 0.7,0),
  ("bridge_snow_a",mcn_no_shadow,"map_river_bridge_snow_a", 1.27,0),

  ("ruins",mcn_no_shadow,"ancient_ruins", 0.45,0),
  ("evil_tower",mcn_no_shadow,"cirithungol", 0.45,0),
  
  ("hill_fort_good",mcn_no_shadow,"dolamroth", 0.45,0),
  ("hill_fort_evil",mcn_no_shadow,"dolguldur", 0.45,0),
  
  ("edoras",mcn_no_shadow,"Edoras", 0.45,0),
  ("rohanTown",mcn_no_shadow,"RohanTown1", 0.45,0),
  ("smallvillage",mcn_no_shadow,"smallvillage", 0.45,0),

  ("orc_fort",mcn_no_shadow,"Fort1", 0.45,0),
  ("ruin_tower",mcn_no_shadow,"orctower_old", 0.45,0),
  ("orctower",mcn_no_shadow,"orctower", 0.45,0),

  ("grove",mcn_no_shadow,"map_forest", 0.45,0),
  ("burial_mound",mcn_no_shadow,"burial_mound", 1.0,0),
  ("tree_low",mcn_no_shadow,"Tree", 0.30,0),
  ("map_tree",mcn_no_shadow,"Tree", 0.45,0),

  ("fountain",mcn_no_shadow,"henneth_annun", 0.45,0),
  
  ("map_prison",mcn_no_shadow,"Lighthouse", 0.45,0),
  ("cave",mcn_no_shadow,"moria", 0.45,0),
  
  ("camp_a",mcn_no_shadow,"nomadcamp_b", 0.45,0),
  ("camp_b",mcn_no_shadow,"nomadcamp", 0.45,0),
  
  ("volcano",mcn_no_shadow,"orodruin", 0.45,0),
  
  ("map_camp_fire",mcn_no_shadow,"pyre", 0.45,0),
  ("map_genie_lamp",mcn_no_shadow,"gold_lamp", 1,0),
  ("map_treasure_chest",mcn_no_shadow,"map_treasure_chest", 0.45,0),
  ("map_f_treasure_chest",mcn_no_shadow,"map_f_treasure_chest", 0.45,0),
  ("map_f_gold",mcn_no_shadow,"map_f_gold", 0.45,0),
  ("map_f_artifact",mcn_no_shadow,"map_f_artifact", 0.45,0),

  ("map_f_obelisk",mcn_no_shadow,"map_f_obelisk", 0.45,0),
  ("map_f_dwarven_treasury",mcn_no_shadow,"quarry_icon", 1.2,0),
  ("map_f_with_hut",mcn_no_shadow,"map_f_with_hut_combined", 0.45,0),
  ("map_f_build_golem_gold",mcn_no_shadow,"map_f_build_golem_gold", 0.45,0),
  ("map_f_learning_stone",mcn_no_shadow,"map_f_learning_stone", 0.45,0),
  ("map_f_library_of_enlightenment",mcn_no_shadow,"map_f_library_of_enlightenment", 0.45,0),
  ("map_f_arena",mcn_no_shadow,"map_f_arena", 0.45,0),
  
  ("map_pyramid",mcn_no_shadow,"map_pyramid", 0.45,0),
  ("map_f_dragon_utopia",mcn_no_shadow,"map_f_dragon_utopia", 0.45,0),
  ("map_f_imp_cache",mcn_no_shadow,"map_f_imp_cache", 0.45,0),
  ("map_f_dragon_fly_hive",mcn_no_shadow,"map_jungle", 0.30,0),
  ("map_f_golem_factory",mcn_no_shadow,"map_f_golem_factory", 0.45,0),
  ("map_f_elemental_conservatory",mcn_no_shadow,"map_f_elemental_conservatory", 0.45,0),
  ("map_f_forsaken_palace",mcn_no_shadow,"map_f_forsaken_palace", 0.45,0),
  ("map_f_crypt",mcn_no_shadow,"map_f_crypt", 0.45,0),
  ("map_f_dragon_vault",mcn_no_shadow,"map_f_dragon_vault", 0.45,0),
  ("map_f_treetop_tower",mcn_no_shadow,"camp_fortified", 1.2,0),
  ("map_f_school_of_magic",mcn_no_shadow,"map_f_school_of_magic", 0.45,0),
  ("map_f_cloud_temple",mcn_no_shadow,"map_f_cloud_temple", 0.45,0),
  ("map_f_dragon_cave",mcn_no_shadow,"map_f_dragon_cave", 0.45,0),
  
  ("map_windmill",mcn_no_shadow,"dedal_map_windmill", 1,0),
  ("map_messenger_post",mcn_no_shadow,"dedal_map_messenger_post", 1,0),
  ("map_tavern",mcn_no_shadow,"dedal_map_tavern_village", 1,0),
  ("map_watchtower",mcn_no_shadow,"dedal_map_watchtower", 1,0),
  
  ("map_battlefield_1",mcn_no_shadow,"dedal_battlefield_a", avatar_scale,0),
  ("map_battlefield_2",mcn_no_shadow,"dedal_battlefield_b", avatar_scale,0),
  ("map_battlefield_3",mcn_no_shadow,"dedal_battlefield_c", avatar_scale,0),
  ("map_battlefield_4",mcn_no_shadow,"dedal_battlefield_d", avatar_scale,0),
  
  ("map_f_portal_1",mcn_no_shadow,"map_f_portal_1", 0.45,0),
  ("map_f_portal_2",mcn_no_shadow,"map_f_portal_2", 0.45,0),
  ("map_f_portal_3",mcn_no_shadow,"map_f_portal_3", 0.45,0),
  ("map_f_portal_4",mcn_no_shadow,"map_f_portal_4", 0.45,0),
  

  ("custom_banner_01",0,"custom_map_banner_01", banner_scale, 0,
   [
     (ti_on_init_map_icon,
      [
        (store_trigger_param_1, ":party_no"),
        (party_get_slot, ":leader_troop", ":party_no", slot_town_lord),
        (try_begin),
          (ge, ":leader_troop", 0),
          (cur_map_icon_set_tableau_material, "tableau_custom_banner_square", ":leader_troop"),
        (try_end),
        ]),
     ]),
  ("custom_banner_02",0,"custom_map_banner_02", banner_scale, 0,
   [
     (ti_on_init_map_icon,
      [
        (store_trigger_param_1, ":party_no"),
        (party_get_slot, ":leader_troop", ":party_no", slot_town_lord),
        (try_begin),
          (ge, ":leader_troop", 0),
          (cur_map_icon_set_tableau_material, "tableau_custom_banner_short", ":leader_troop"),
        (try_end),
        ]),
     ]),
  ("custom_banner_03",0,"custom_map_banner_03", banner_scale, 0,
   [
     (ti_on_init_map_icon,
      [
        (store_trigger_param_1, ":party_no"),
        (party_get_slot, ":leader_troop", ":party_no", slot_town_lord),
        (try_begin),
          (ge, ":leader_troop", 0),
          (cur_map_icon_set_tableau_material, "tableau_custom_banner_tall", ":leader_troop"),
        (try_end),
        ]),
     ]),
  ("bandit_lair",mcn_no_shadow,"map_bandit_lair", 0.45, 0),

  # Banners
  ("banner_01",0,"map_flag_01", banner_scale,0),
  ("banner_02",0,"map_flag_02", banner_scale,0),
  ("banner_03",0,"map_flag_03", banner_scale,0),
  ("banner_04",0,"map_flag_04", banner_scale,0),
  ("banner_05",0,"map_flag_05", banner_scale,0),
  ("banner_06",0,"map_flag_06", banner_scale,0),
  ("banner_07",0,"map_flag_07", banner_scale,0),
  ("banner_08",0,"map_flag_08", banner_scale,0),
  ("banner_09",0,"map_flag_09", banner_scale,0),
  ("banner_10",0,"map_flag_10", banner_scale,0),
  ("banner_11",0,"map_flag_11", banner_scale,0),
  ("banner_12",0,"map_flag_12", banner_scale,0),
  ("banner_13",0,"map_flag_13", banner_scale,0),
  ("banner_14",0,"map_flag_14", banner_scale,0),
  ("banner_15",0,"map_flag_f21", banner_scale,0),
  ("banner_16",0,"map_flag_16", banner_scale,0),
  ("banner_17",0,"map_flag_17", banner_scale,0),
  ("banner_18",0,"map_flag_18", banner_scale,0),
  ("banner_19",0,"map_flag_19", banner_scale,0),
  ("banner_20",0,"map_flag_20", banner_scale,0),
  ("banner_21",0,"map_flag_21", banner_scale,0),
  
  ("banner_22",0,"map_flag_22", banner_scale,0),
  ("banner_23",0,"map_flag_23", banner_scale,0),
  ("banner_24",0,"map_flag_24", banner_scale,0),
  ("banner_25",0,"map_flag_25", banner_scale,0),
  ("banner_26",0,"map_flag_26", banner_scale,0),
  ("banner_27",0,"map_flag_27", banner_scale,0),
  ("banner_28",0,"map_flag_28", banner_scale,0),
  ("banner_29",0,"map_flag_29", banner_scale,0),
  ("banner_30",0,"map_flag_30", banner_scale,0),
  ("banner_31",0,"map_flag_31", banner_scale,0),
  ("banner_32",0,"map_flag_32", banner_scale,0),
  ("banner_33",0,"map_flag_33", banner_scale,0),
  ("banner_34",0,"map_flag_34", banner_scale,0),
  ("banner_35",0,"map_flag_35", banner_scale,0),
  ("banner_36",0,"map_flag_36", banner_scale,0),
  ("banner_37",0,"map_flag_37", banner_scale,0),
  ("banner_38",0,"map_flag_38", banner_scale,0),
  ("banner_39",0,"map_flag_39", banner_scale,0),
  ("banner_40",0,"map_flag_40", banner_scale,0),
  ("banner_41",0,"map_flag_41", banner_scale,0),
  ("banner_42",0,"map_flag_42", banner_scale,0),
  
  ("banner_43",0,"map_flag_43", banner_scale,0),
  ("banner_44",0,"map_flag_44", banner_scale,0),
  ("banner_45",0,"map_flag_45", banner_scale,0),
  ("banner_46",0,"map_flag_46", banner_scale,0),
  ("banner_47",0,"map_flag_47", banner_scale,0),
  ("banner_48",0,"map_flag_48", banner_scale,0),
  ("banner_49",0,"map_flag_49", banner_scale,0),
  ("banner_50",0,"map_flag_50", banner_scale,0),
  ("banner_51",0,"map_flag_51", banner_scale,0),
  ("banner_52",0,"map_flag_52", banner_scale,0),
  ("banner_53",0,"map_flag_53", banner_scale,0),
  ("banner_54",0,"map_flag_54", banner_scale,0),
  ("banner_55",0,"map_flag_55", banner_scale,0),
  ("banner_56",0,"map_flag_56", banner_scale,0),
  ("banner_57",0,"map_flag_57", banner_scale,0),
  ("banner_58",0,"map_flag_58", banner_scale,0),
  ("banner_59",0,"map_flag_59", banner_scale,0),
  ("banner_60",0,"map_flag_60", banner_scale,0),
  ("banner_61",0,"map_flag_61", banner_scale,0),
  ("banner_62",0,"map_flag_62", banner_scale,0),
  ("banner_63",0,"map_flag_63", banner_scale,0),
  
  ("banner_64",0,"map_flag_d01", banner_scale,0),
  ("banner_65",0,"map_flag_d02", banner_scale,0),
  ("banner_66",0,"map_flag_d03", banner_scale,0),
  ("banner_67",0,"map_flag_d04", banner_scale,0),
  ("banner_68",0,"map_flag_d05", banner_scale,0),
  ("banner_69",0,"map_flag_d06", banner_scale,0),
  ("banner_70",0,"map_flag_d07", banner_scale,0),
  ("banner_71",0,"map_flag_d08", banner_scale,0),
  ("banner_72",0,"map_flag_d09", banner_scale,0),
  ("banner_73",0,"map_flag_d10", banner_scale,0),
  ("banner_74",0,"map_flag_d11", banner_scale,0),
  ("banner_75",0,"map_flag_d12", banner_scale,0),
  ("banner_76",0,"map_flag_d13", banner_scale,0),
  ("banner_77",0,"map_flag_d14", banner_scale,0),
  ("banner_78",0,"map_flag_d15", banner_scale,0),
  ("banner_79",0,"map_flag_d16", banner_scale,0),
  ("banner_80",0,"map_flag_d17", banner_scale,0),
  
  ("banner_81",0,"map_flag_d18", banner_scale,0),
  ("banner_82",0,"map_flag_d19", banner_scale,0),
  ("banner_83",0,"map_flag_d20", banner_scale,0),
  ("banner_84",0,"map_flag_d21", banner_scale,0),
  ("banner_85",0,"map_flag_e01", banner_scale,0),
  ("banner_86",0,"map_flag_e02", banner_scale,0),
  ("banner_87",0,"map_flag_e03", banner_scale,0),
  ("banner_88",0,"map_flag_e04", banner_scale,0),
  ("banner_89",0,"map_flag_e05", banner_scale,0),
  ("banner_90",0,"map_flag_e06", banner_scale,0),
  ("banner_91",0,"map_flag_e07", banner_scale,0),
  ("banner_92",0,"map_flag_e08", banner_scale,0),
  ("banner_93",0,"map_flag_e09", banner_scale,0),
  ("banner_94",0,"map_flag_e10", banner_scale,0),
  ("banner_95",0,"map_flag_e11", banner_scale,0),
  ("banner_96",0,"map_flag_e12", banner_scale,0),
  ("banner_97",0,"map_flag_e13", banner_scale,0),
  ("banner_98",0,"map_flag_e14", banner_scale,0),
  ("banner_99",0,"map_flag_e15", banner_scale,0),
  
  ("banner_100",0,"map_flag_e16", banner_scale,0),
  ("banner_101",0,"map_flag_e17", banner_scale,0),
  ("banner_102",0,"map_flag_e18", banner_scale,0),
  ("banner_103",0,"map_flag_e19", banner_scale,0),
  ("banner_104",0,"map_flag_e20", banner_scale,0),
  ("banner_105",0,"map_flag_e21", banner_scale,0),

  ("banner_106",0,"map_flag_f01", banner_scale,0),
  ("banner_107",0,"map_flag_f02", banner_scale,0),
  ("banner_108",0,"map_flag_f03", banner_scale,0),
  ("banner_109",0,"map_flag_f04", banner_scale,0),
  ("banner_110",0,"map_flag_f05", banner_scale,0),
  ("banner_111",0,"map_flag_f06", banner_scale,0),
  ("banner_112",0,"map_flag_f07", banner_scale,0),
  ("banner_113",0,"map_flag_f08", banner_scale,0),
  ("banner_114",0,"map_flag_f09", banner_scale,0),
  ("banner_115",0,"map_flag_f10", banner_scale,0),
  ("banner_116",0,"map_flag_f11", banner_scale,0),
  ("banner_117",0,"map_flag_f12", banner_scale,0),
  ("banner_118",0,"map_flag_f13", banner_scale,0),
  ("banner_119",0,"map_flag_f14", banner_scale,0),
  ("banner_120",0,"map_flag_f15", banner_scale,0),
  ("banner_121",0,"map_flag_f16", banner_scale,0),
  ("banner_122",0,"map_flag_f17", banner_scale,0),
  ("banner_123",0,"map_flag_f18", banner_scale,0),
  ("banner_124",0,"map_flag_f19", banner_scale,0),
  ("banner_125",0,"map_flag_f20", banner_scale,0),

  ("banner_g01", 0, "map_flag_g01", banner_scale,0),
  ("banner_g02", 0, "map_flag_g02", banner_scale,0),
  ("banner_g03", 0, "map_flag_g03", banner_scale,0),
  ("banner_g04", 0, "map_flag_g04", banner_scale,0),
  ("banner_g05", 0, "map_flag_g05", banner_scale,0),
  ("banner_g06", 0, "map_flag_g06", banner_scale,0),
  ("banner_g07", 0, "map_flag_g07", banner_scale,0),
  ("banner_g08", 0, "map_flag_g08", banner_scale,0),
  ("banner_g09", 0, "map_flag_g09", banner_scale,0),
  ("banner_g10", 0, "map_flag_g10", banner_scale,0),
  ("banner_g11", 0, "map_flag_g11", banner_scale,0),
  ("banner_g12", 0, "map_flag_g12", banner_scale,0),
  ("banner_g13", 0, "map_flag_g13", banner_scale,0),
  ("banner_g14", 0, "map_flag_g14", banner_scale,0),
  ("banner_g15", 0, "map_flag_g15", banner_scale,0),
  ("banner_g16", 0, "map_flag_g16", banner_scale,0),
  ("banner_g17", 0, "map_flag_g17", banner_scale,0),
  ("banner_g18", 0, "map_flag_g18", banner_scale,0),
  ("banner_g19", 0, "map_flag_g19", banner_scale,0),
  ("banner_g20", 0, "map_flag_g20", banner_scale,0),
  ("banner_g21", 0, "map_flag_g21", banner_scale,0),
  
  ("banner_h01", 0, "map_flag_h01", banner_scale,0),
  ("banner_h02", 0, "map_flag_h02", banner_scale,0),
  ("banner_h03", 0, "map_flag_h03", banner_scale,0),
  ("banner_h04", 0, "map_flag_h04", banner_scale,0),
  ("banner_h05", 0, "map_flag_h05", banner_scale,0),
  ("banner_h06", 0, "map_flag_h06", banner_scale,0),
  ("banner_h07", 0, "map_flag_h07", banner_scale,0),
  ("banner_h08", 0, "map_flag_h08", banner_scale,0),
  ("banner_h09", 0, "map_flag_h09", banner_scale,0),
  ("banner_h10", 0, "map_flag_h10", banner_scale,0),
  ("banner_h11", 0, "map_flag_h11", banner_scale,0),
  ("banner_h12", 0, "map_flag_h12", banner_scale,0),
  ("banner_h13", 0, "map_flag_h13", banner_scale,0),
  ("banner_h14", 0, "map_flag_h14", banner_scale,0),
  ("banner_h15", 0, "map_flag_h15", banner_scale,0),
  ("banner_h16", 0, "map_flag_h16", banner_scale,0),
  ("banner_h17", 0, "map_flag_h17", banner_scale,0),
  ("banner_h18", 0, "map_flag_h18", banner_scale,0),
  ("banner_h19", 0, "map_flag_h19", banner_scale,0),
  ("banner_h20", 0, "map_flag_h20", banner_scale,0),
  ("banner_h21", 0, "map_flag_h21", banner_scale,0),

  ("banner_i01", 0, "map_flag_i01", banner_scale,0),
  ("banner_i02", 0, "map_flag_i02", banner_scale,0),
  ("banner_i03", 0, "map_flag_i03", banner_scale,0),
  ("banner_i04", 0, "map_flag_i04", banner_scale,0),
  ("banner_i05", 0, "map_flag_i05", banner_scale,0),
  ("banner_i06", 0, "map_flag_i06", banner_scale,0),
  ("banner_i07", 0, "map_flag_i07", banner_scale,0),
  ("banner_i08", 0, "map_flag_i08", banner_scale,0),
  ("banner_i09", 0, "map_flag_i09", banner_scale,0),
  ("banner_i10", 0, "map_flag_i10", banner_scale,0),
  ("banner_i11", 0, "map_flag_i11", banner_scale,0),
  ("banner_i12", 0, "map_flag_i12", banner_scale,0),
  ("banner_i13", 0, "map_flag_i13", banner_scale,0),
  ("banner_i14", 0, "map_flag_i14", banner_scale,0),
  ("banner_i15", 0, "map_flag_i15", banner_scale,0),
  ("banner_i16", 0, "map_flag_i16", banner_scale,0),
  ("banner_i17", 0, "map_flag_i17", banner_scale,0),
  ("banner_i18", 0, "map_flag_i18", banner_scale,0),
  ("banner_i19", 0, "map_flag_i19", banner_scale,0),
  ("banner_i20", 0, "map_flag_i20", banner_scale,0),
  ("banner_i21", 0, "map_flag_i21", banner_scale,0),
  
  ("banner_j01", 0, "map_flag_j01", banner_scale,0),
  ("banner_j02", 0, "map_flag_j02", banner_scale,0),
  ("banner_j03", 0, "map_flag_j03", banner_scale,0),
  ("banner_j04", 0, "map_flag_j04", banner_scale,0),
  ("banner_j05", 0, "map_flag_j05", banner_scale,0),
  ("banner_j06", 0, "map_flag_j06", banner_scale,0),
  ("banner_j07", 0, "map_flag_j07", banner_scale,0),
  ("banner_j08", 0, "map_flag_j08", banner_scale,0),
  ("banner_j09", 0, "map_flag_j09", banner_scale,0),
  ("banner_j10", 0, "map_flag_j10", banner_scale,0),
  ("banner_j11", 0, "map_flag_j11", banner_scale,0),
  ("banner_j12", 0, "map_flag_j12", banner_scale,0),
  ("banner_j13", 0, "map_flag_j13", banner_scale,0),
  ("banner_j14", 0, "map_flag_j14", banner_scale,0),
  ("banner_j15", 0, "map_flag_j15", banner_scale,0),
  ("banner_j16", 0, "map_flag_j16", banner_scale,0),
  ("banner_j17", 0, "map_flag_j17", banner_scale,0),
  ("banner_j18", 0, "map_flag_j18", banner_scale,0),
  ("banner_j19", 0, "map_flag_j19", banner_scale,0),
  ("banner_j20", 0, "map_flag_j20", banner_scale,0),
  ("banner_j21", 0, "map_flag_j21", banner_scale,0),

  ("banner_k01", 0, "map_flag_k01", banner_scale,0),
  ("banner_k02", 0, "map_flag_k02", banner_scale,0),
  ("banner_k03", 0, "map_flag_k03", banner_scale,0),
  ("banner_k04", 0, "map_flag_k04", banner_scale,0),
  ("banner_k05", 0, "map_flag_k05", banner_scale,0),
  ("banner_k06", 0, "map_flag_k06", banner_scale,0),
  ("banner_k07", 0, "map_flag_k07", banner_scale,0),
  ("banner_k08", 0, "map_flag_k08", banner_scale,0),
  ("banner_k09", 0, "map_flag_k09", banner_scale,0),
  ("banner_k10", 0, "map_flag_k10", banner_scale,0),
  ("banner_k11", 0, "map_flag_k11", banner_scale,0),
  ("banner_k12", 0, "map_flag_k12", banner_scale,0),
  ("banner_k13", 0, "map_flag_k13", banner_scale,0),
  ("banner_k14", 0, "map_flag_k14", banner_scale,0),
  ("banner_k15", 0, "map_flag_k15", banner_scale,0),
  ("banner_k16", 0, "map_flag_k16", banner_scale,0),
  ("banner_k17", 0, "map_flag_k17", banner_scale,0),
  ("banner_k18", 0, "map_flag_k18", banner_scale,0),
  ("banner_k19", 0, "map_flag_k19", banner_scale,0),
  ("banner_k20", 0, "map_flag_k20", banner_scale,0),
  ("banner_k21", 0, "map_flag_k21", banner_scale,0),

  ("banner_m01", 0, "map_flag_m01", banner_scale,0),
  ("banner_m02", 0, "map_flag_m02", banner_scale,0),
  ("banner_m03", 0, "map_flag_m03", banner_scale,0),
  ("banner_m04", 0, "map_flag_m04", banner_scale,0),
  ("banner_m05", 0, "map_flag_m05", banner_scale,0),
  ("banner_m06", 0, "map_flag_m06", banner_scale,0),
  ("banner_m07", 0, "map_flag_m07", banner_scale,0),
  ("banner_m08", 0, "map_flag_m08", banner_scale,0),
  ("banner_m09", 0, "map_flag_m09", banner_scale,0),
  ("banner_m10", 0, "map_flag_m10", banner_scale,0),
  ("banner_m11", 0, "map_flag_m11", banner_scale,0),
  ("banner_m12", 0, "map_flag_m12", banner_scale,0),
  ("banner_m13", 0, "map_flag_m13", banner_scale,0),
  ("banner_m14", 0, "map_flag_m14", banner_scale,0),
  ("banner_m15", 0, "map_flag_m15", banner_scale,0),
  ("banner_m16", 0, "map_flag_m16", banner_scale,0),
  ("banner_m17", 0, "map_flag_m17", banner_scale,0),
  ("banner_m18", 0, "map_flag_m18", banner_scale,0),
  ("banner_m19", 0, "map_flag_m19", banner_scale,0),
  ("banner_m20", 0, "map_flag_m20", banner_scale,0),
  ("banner_m21", 0, "map_flag_m21", banner_scale,0),

  ("banner_l01", 0, "map_flag_l01", banner_scale,0),
  ("banner_l02", 0, "map_flag_l02", banner_scale,0),
  ("banner_l03", 0, "map_flag_l03", banner_scale,0),
  ("banner_l04", 0, "map_flag_l04", banner_scale,0),
  ("banner_l05", 0, "map_flag_l05", banner_scale,0),
  ("banner_l06", 0, "map_flag_l06", banner_scale,0),
  ("banner_l07", 0, "map_flag_l07", banner_scale,0),
  ("banner_l08", 0, "map_flag_l08", banner_scale,0),
  ("banner_l09", 0, "map_flag_l09", banner_scale,0),
  ("banner_l10", 0, "map_flag_l10", banner_scale,0),
  ("banner_l11", 0, "map_flag_l11", banner_scale,0),
  ("banner_l12", 0, "map_flag_l12", banner_scale,0),
  ("banner_l13", 0, "map_flag_l13", banner_scale,0),
  ("banner_l14", 0, "map_flag_l14", banner_scale,0),
  ("banner_l15", 0, "map_flag_l15", banner_scale,0),
  ("banner_l16", 0, "map_flag_l16", banner_scale,0),
  ("banner_l17", 0, "map_flag_l17", banner_scale,0),
  ("banner_l18", 0, "map_flag_l18", banner_scale,0),
  ("banner_l19", 0, "map_flag_l19", banner_scale,0),
  ("banner_l20", 0, "map_flag_l20", banner_scale,0),
  ("banner_l21", 0, "map_flag_l21", banner_scale,0),
  
  ("banner_n01", 0, "map_flag_n01", banner_scale,0),
  ("banner_n02", 0, "map_flag_n02", banner_scale,0),
  ("banner_n03", 0, "map_flag_n03", banner_scale,0),
  ("banner_n04", 0, "map_flag_n04", banner_scale,0),
  ("banner_n05", 0, "map_flag_n05", banner_scale,0),
  ("banner_n06", 0, "map_flag_n06", banner_scale,0),
  ("banner_n07", 0, "map_flag_n07", banner_scale,0),
  ("banner_n08", 0, "map_flag_n08", banner_scale,0),
  ("banner_n09", 0, "map_flag_n09", banner_scale,0),
  ("banner_n10", 0, "map_flag_n10", banner_scale,0),
  ("banner_n11", 0, "map_flag_n11", banner_scale,0),
  ("banner_n12", 0, "map_flag_n12", banner_scale,0),
  ("banner_n13", 0, "map_flag_n13", banner_scale,0),
  ("banner_n14", 0, "map_flag_n14", banner_scale,0),
  ("banner_n15", 0, "map_flag_n15", banner_scale,0),
  ("banner_n16", 0, "map_flag_n16", banner_scale,0),
  ("banner_n17", 0, "map_flag_n17", banner_scale,0),
  ("banner_n18", 0, "map_flag_n18", banner_scale,0),
  ("banner_n19", 0, "map_flag_n19", banner_scale,0),
  ("banner_n20", 0, "map_flag_n20", banner_scale,0),
  ("banner_n21", 0, "map_flag_n21", banner_scale,0),
  
  ("map_flag_kingdom_a",0,"map_flag_kingdom_a", banner_scale,0),
  ("map_flag_kingdom_b",0,"map_flag_kingdom_b", banner_scale,0),
  ("map_flag_kingdom_c",0,"map_flag_kingdom_c", banner_scale,0),
  ("map_flag_kingdom_d",0,"map_flag_kingdom_d", banner_scale,0),
  ("map_flag_kingdom_e",0,"map_flag_kingdom_e", banner_scale,0),
  ("map_flag_kingdom_f",0,"map_flag_kingdom_f", banner_scale,0),

  ("map_flag_kingdom_1",0,"map_flag_kingdom_1", banner_scale,0),
  ("map_flag_kingdom_2",0,"map_flag_kingdom_2", banner_scale,0),
  ("map_flag_kingdom_3",0,"map_flag_kingdom_3", banner_scale,0),
  ("map_flag_kingdom_4",0,"map_flag_kingdom_4", banner_scale,0),
  ("map_flag_kingdom_5",0,"map_flag_kingdom_5", banner_scale,0),
  ("map_flag_kingdom_6",0,"map_flag_kingdom_6", banner_scale,0),
  ("map_flag_kingdom_7",0,"map_flag_kingdom_7", banner_scale,0),
  ("map_flag_kingdom_8",0,"map_flag_kingdom_8", banner_scale,0),
  ("map_flag_kingdom_9",0,"map_flag_kingdom_9", banner_scale,0),
  ("map_flag_kingdom_10",0,"map_flag_kingdom_10", banner_scale,0),
  ("map_flag_kingdom_11",0,"map_flag_kingdom_11", banner_scale,0),
  ("map_flag_kingdom_12",0,"map_flag_kingdom_12", banner_scale,0),
  ("map_flag_kingdom_13",0,"map_flag_kingdom_14", banner_scale,0),
  ("banner_136",0,"map_flag_15", banner_scale,0),
  ## CC
  ("map_flag_bandit_f",0,"map_flag_bandit_f", banner_scale,0),
  ("map_flag_bandit_b",0,"map_flag_bandit_b", banner_scale,0),
  ("map_flag_bandit_c",0,"map_flag_bandit_c", banner_scale,0),
  ("map_flag_bandit_a",0,"map_flag_bandit_a", banner_scale,0),
  ("map_flag_bandit_d",0,"map_flag_bandit_d", banner_scale,0),
  ("map_flag_bandit_e",0,"map_flag_bandit_e", banner_scale,0),
  ## CC
]
# modmerger_start version=201 type=2
try:
    component_name = "map_icons"
    var_set = { "map_icons" : map_icons }
    from modmerger import modmerge
    modmerge(var_set)
except:
    raise
# modmerger_end
