automatic_fire_right_ckick = (
    0.1, 0, 0,
   [   ],
   [
    (get_player_agent_no, ":attacker_agent"), 
    (set_fixed_point_multiplier, 1),
      (agent_get_wielded_item, ":agent_cur_weapon", ":attacker_agent", 0),
      (gt,":agent_cur_weapon", 0),
      (item_get_type, ":cur_weapon_type", ":agent_cur_weapon"),
      
      
      
      
      
      (this_or_next|eq,":cur_weapon_type",itp_type_pistol),
      (this_or_next|eq,":cur_weapon_type",itp_type_crossbow),
      (eq,":cur_weapon_type",itp_type_musket),

      
      
      (agent_get_attack_action, ":attack_action", ":attacker_agent"),
      (try_begin),
        (neg|game_key_is_down, gk_attack),
        (game_key_is_down, gk_defend),
        #(eq, ":attack_action", 1),
        #ticker trigger
        (agent_get_slot,":ticker_time",":attacker_agent",slot_agent_shoot_time_ticker),
        (try_begin),
          (le,":ticker_time",0),      
          
          #ticker trigger
          (item_get_speed_rating, ":ticker_time", ":agent_cur_weapon"),
          (val_max,":ticker_time",1),
          (store_div,":ticker_time",200,":ticker_time"),
          (agent_set_slot,":attacker_agent",slot_agent_shoot_time_ticker,":ticker_time"),    
            
          (assign,":cur_weapon_slot",-1),
          (assign,":item_slot_num",4),
          (try_for_range,":cur_item_slot",0,":item_slot_num"),
            (eq,":cur_weapon_slot",-1),
            (agent_get_item_slot, ":item_no", ":attacker_agent", ":cur_item_slot"),
            (eq,":item_no",":agent_cur_weapon"),
            (assign,":cur_weapon_slot",":cur_item_slot"),
            (assign,":item_slot_num", 0),
          (try_end),
                    
          (agent_get_item_cur_ammo, ":cur_ammo", ":attacker_agent",":cur_weapon_slot"),
          (gt,":cur_ammo",0),
          (val_sub,":cur_ammo",1),
          (try_begin),
            (this_or_next|eq,":agent_cur_weapon","itm_power_musket_8barrel"),
            (eq,":agent_cur_weapon","itm_zlmg"),
            (val_add,":cur_ammo",1),
          (try_end),
          (agent_set_ammo,":attacker_agent",":agent_cur_weapon",":cur_ammo"),
                    
          (try_begin),
            (this_or_next|eq,":cur_weapon_type",itp_type_pistol),
            (eq,":cur_weapon_type",itp_type_musket),
            (assign,":cur_ammo_type",itp_type_bullets),
            (assign,":cur_ammo_id","itm_cartridges"),#as default
          (else_try),
            (assign,":cur_ammo_type",itp_type_bolts),
            (assign,":cur_ammo_id","itm_bolts"),#as default
          (try_end),
          #match the right ammmo type
          (assign,":item_slot_num",4),
          (try_for_range,":cur_item_slot",0,":item_slot_num"),
            (agent_get_item_slot, ":item_no", ":attacker_agent", ":cur_item_slot"),
            (gt,":item_no",-1),
            (item_get_type, ":item_type_2", ":item_no"),
            (eq,":item_type_2",":cur_ammo_type"),
            (agent_get_item_cur_ammo, ":cur_ammo", ":attacker_agent", ":cur_item_slot"),
            (gt,":cur_ammo",0),
            (assign,":cur_ammo_id",":item_no"),
            (assign,":item_slot_num",0),#break
          (try_end),
          
          
          #reduce ammo
          (assign,":killed",1),
          (try_begin),
            (eq,":agent_cur_weapon","itm_van_helsing_crossbow"),
            (assign,":killed",3),
          (else_try),
            (eq,":agent_cur_weapon","itm_van_helsing_crossbow_auto"),
            (assign,":killed",2),
          (else_try),
            (eq,":agent_cur_weapon","itm_rat_musket_8barrel"),
            (assign,":killed",2),
          (else_try),
            (eq,":agent_cur_weapon","itm_power_musket_8barrel"),
            (assign,":killed",4),
          (else_try),
            (neq,":cur_ammo_id","itm_cartridges_burst"),
            (eq,":agent_cur_weapon","itm_drawf_musket_8barrel2"),
            (assign,":killed",3),
          (else_try),
            (eq,":cur_ammo_id","itm_cartridges_burst"),
            (eq,":agent_cur_weapon","itm_drawf_musket_8barrel2"),
            (assign,":killed",4),
          (else_try),
            (eq,":cur_ammo_id","itm_cartridges_burst"),
            (eq,":agent_cur_weapon","itm_drawf_musket_8barrel1"),
            (assign,":killed",2),
          (else_try),
            (eq,":cur_ammo_id","itm_cartridges_burst"),
            (eq,":agent_cur_weapon","itm_zlmg"),
            (assign,":killed",2),
          (else_try),
            (eq,":cur_ammo_id","itm_cartridges_burst"),
            (eq,":agent_cur_weapon","itm_sissofbattle_A295"),
            (assign,":killed",4),
          (try_end),
          
          #get original position of weapon
          (agent_get_look_position,pos23,":attacker_agent"),
          
          (agent_get_bone_position, pos24, ":attacker_agent", 9, 1),
          (position_move_z, pos24, 30, 1),
          (position_copy_rotation,pos24,pos23),

          #(position_move_y, pos24,130),
          #(agent_get_horse,":attacker_agent_horse",":attacker_agent"),
          #(agent_get_animation, ":attacker_animation", ":attacker_agent", 0),
          #(try_begin),
          #    (this_or_next|eq,":attacker_animation","anim_walk_forward_crouch"),
          #    (eq,":attacker_animation","anim_stand_to_crouch"),
          #    (position_move_z,pos24,115,1),
          #(else_try),
          #  (lt,":attacker_agent_horse",0),
          #  (position_move_z,pos24,170,1),
          #(else_try),
          #  (position_move_z,pos24,270,1),
          #(try_end),

          ##get weapon position after calculating accuracy
          (set_fixed_point_multiplier, 1),
          (item_get_missile_speed, ":bullet_speed", ":agent_cur_weapon"),
             (try_begin),
               (le,":bullet_speed",0),
               (assign,":bullet_speed",150),
             (try_end),
          (try_begin),
              (eq,":flame_ammo",0),
             (eq,":cur_weapon_type",itp_type_musket),
             (play_sound_at_position, "snd_release_musket", pos24),
             (copy_position,pos5,pos24),
             (position_move_x,pos5,0),
             (position_move_y,pos5,130),
             (particle_system_burst_no_sync,"psys_musket_smoke",pos5,2),
             (particle_system_burst_no_sync,"psys_musket_ogon",pos5,3),
             (particle_system_burst_no_sync,"psys_musket_svet",pos5,3),   

             (position_move_x, pos5, -4),
             (position_move_y, pos5,-120),
             (position_move_z, pos5,3),
             (particle_system_burst_no_sync, "psys_musket_powder_a", pos5, 2),
             (particle_system_burst_no_sync, "psys_pistol_powder_b", pos5, 3),
             (agent_set_animation, ":attacker_agent", "anim_release_musket", 1),
             (try_begin),
               (le,":bullet_speed",0),
               (assign,":bullet_speed",150),
             (try_end),
          (else_try), 
              (eq,":flame_ammo",0),
             (eq,":cur_weapon_type",itp_type_pistol),
             (play_sound_at_position, "snd_release_musket", pos24),
             (copy_position,pos5,pos24),
             
             (position_move_x,pos5,27),
             (position_move_y,pos5,36),
             (particle_system_burst_no_sync,"psys_pistol_smoke",pos5,1),
             (particle_system_burst_no_sync,"psys_pistol_ogon",pos5,4),
             (particle_system_burst_no_sync,"psys_pistol_svet",pos5,4),   

             (position_move_x, pos5,-30),
             (position_move_y, pos5,-30),
             (position_move_z, pos5,3),
             (particle_system_burst_no_sync, "psys_musket_powder_a", pos5, 1),
             (particle_system_burst_no_sync, "psys_pistol_powder_b", pos5, 2),
             (agent_set_animation, ":attacker_agent", "anim_release_pistol", 1),
          (else_try), 
              (eq,":flame_ammo",0),
             (play_sound_at_position, "snd_release_crossbow", pos24),
             (agent_set_animation, ":attacker_agent", "anim_release_crossbow", 1),
          (try_end),
          (item_get_accuracy, ":accuracy", ":agent_cur_weapon"),
          (try_for_range, ":unused", 0, ":killed"),
            (copy_position,pos25,pos24),
            (val_add,":bullet_speed",-3),
            (val_max,":accuracy",1),
            (store_div,":randomize_value",300,":accuracy"),
            (store_random_in_range,":z",0,":randomize_value"),
            (store_random_in_range,":x",0,":randomize_value"),
            (position_rotate_z,pos25,":z"),
            (position_rotate_x,pos25,":x"),          
            (add_missile, ":attacker_agent", pos25, ":bullet_speed", ":agent_cur_weapon", 0, ":cur_ammo_id",0),
          (try_end),
        (else_try),
          (val_sub,":ticker_time",1),
          (agent_set_slot,":attacker_agent",slot_agent_shoot_time_ticker,":ticker_time"),
        (try_end),     
      (else_try),
        (agent_get_defend_action, ":defend_action_state", ":attacker_agent"),
        (this_or_next|gt,":defend_action_state",0),
        (gt,":attack_action",1),
        
        (game_key_is_down, gk_attack),
        (neg|game_key_is_down, gk_defend),
        
        (item_get_speed_rating, ":ticker_time", ":agent_cur_weapon"),
        (val_max,":ticker_time",1),
        (store_div,":ticker_time",800,":ticker_time"),
        (agent_set_slot,":attacker_agent",slot_agent_shoot_time_ticker,":ticker_time"),      
      (try_end),
    (try_end),
   ]
)
