   ("cf_agent_dragon_voice",
    [
      (store_script_param, ":shooter",1),
      (store_script_param, ":type",2),
      (try_begin),
        (get_player_agent_no,":player"),
        (eq,":shooter",":player"),
        (this_or_next|key_clicked, "$key_special_4"),
        (key_clicked, "$key_special_2"),
        (agent_get_horse, ":horse_agent", ":shooter"),
        (lt, ":horse_agent", 0),
        (agent_set_animation, ":shooter", "anim_warcry",1),  
      (else_try),
        (agent_get_horse, ":horse_agent", ":shooter"),
        (lt, ":horse_agent", 0),
        (agent_set_animation, ":shooter", "anim_warcry",1), 
      (try_end),
     
      (agent_get_look_position,pos5,":shooter"),
      (agent_get_position,pos4,":shooter"),
      (position_copy_rotation,pos4,pos5),
      (agent_get_troop_id, ":troop_no", ":shooter"),
      (store_skill_level, ":power", skl_magic_power, ":troop_no"),
      (store_character_level,":ch_bonus",":troop_no"),
            
      (agent_get_horse,":horse",":agent_summon"),
      (copy_position,pos51,pos4),
      (try_begin), 
        (gt, ":horse", -1),
        (position_move_z,pos51,270),
      (else_try),
        (neg|gt, ":horse", -1),
        (position_move_z,pos51,170),
      (try_end),
      (position_move_z,pos51,150),
      (position_move_y,pos51,150),
            
      (try_begin),
        (get_player_agent_no,":player"),
        (eq,":shooter",":player"),
        (eq, "$skill_mask_start", 1),
        (key_is_down, key_left_shift),
        (assign, "$skill_mask_start", 0),
        (copy_position, pos51, pos43),
      (try_end),
           
      (assign,":voice_type",-1),
      
      (try_begin),
        (eq, ":type", "itm_voice_clear_skies"),
        (agent_play_sound,":shooter","snd_voice_clear_skies"),
        (try_for_agents,":agent"),
          (agent_is_alive,":agent"),
          (agent_is_human,":agent"),
          
          (agent_get_position, pos2, ":agent"),
          (position_set_z_to_ground_level, pos2),
          (position_set_z_to_ground_level, pos4),
          (neg|position_is_behind_position, pos2, pos4),
          (get_distance_between_positions, ":range", pos2, pos4),
          (neg|gt, ":range", 500),
          
          (try_begin),
            (this_or_next|agent_is_ally,":shooter"),
            (agent_is_ally,":agent"),
            (this_or_next|neg|agent_is_ally,":agent"),
            (neg|agent_is_ally,":shooter"),  
            
            (try_begin),
              (agent_get_slot, ":timer_2", ":agent", slot_agent_is_fly),
              (gt, ":timer_2", 0),
              (agent_set_slot, ":agent", slot_agent_is_fly, 0),
            (try_end),    
                
            (agent_get_position, pos22, ":agent"),
            (agent_set_animation, ":agent", "anim_explove_fly"),
            (position_move_z, pos22, 200),
            (particle_system_burst, "psys_stun_effect", pos22, 1),
            (agent_deliver_damage_to_agent, ":shooter", ":agent", 50),
          (try_end),      
          

          (try_begin),
            (this_or_next|agent_is_ally,":shooter"),
            (agent_is_ally,":agent"),
            (this_or_next|neg|agent_is_ally,":agent"),
            (neg|agent_is_ally,":shooter"),      
            (agent_slot_ge, ":agent", slot_agent_spawned, 1), 
            (agent_fade_out, ":agent"),
          (try_end),      
        (try_end),      
      (else_try),
        (eq, ":type", "itm_voice_cyclone"),
        (agent_play_sound,":shooter","snd_voice_cyclone"),
        (assign,":voice_type",2),
      (else_try),
        (eq, ":type", "itm_voice_unrelenting_force"),
        (agent_play_sound,":shooter","snd_voice_unrelenting_force"),
        (assign,":voice_type",1),
      (else_try),#itm_voice_become_ethereal
        (eq, ":type", "itm_voice_become_ethereal"),
        (agent_play_sound,":shooter","snd_voice_become_ethereal"),
        (agent_set_slot, ":shooter", slot_agent_special_ability_affect_type, "itm_voice_become_ethereal"),
        (agent_set_slot, ":shooter", slot_agent_special_ability_affect_time, 10),
      (else_try),#itm_voice_slow_time
        (eq, ":type", "itm_voice_slow_time"),
        (agent_play_sound,":shooter","snd_voice_slow_time"),
        (call_script, "script_cf_agent_mass_slow", ":shooter"),
      (else_try),#itm_voice_whirlwind_sprint
        (eq, ":type", "itm_voice_whirlwind_sprint"),
        (agent_play_sound,":shooter","snd_voice_whirlwind_sprint"),
        (call_script, "script_cf_agent_rush", ":shooter"),
      (else_try),#itm_voice_animal_allegiance
        (eq, ":type", "itm_voice_animal_allegiance"),
        (agent_play_sound,":shooter","snd_voice_animal_allegiance"),
        (store_character_level,":troop_level",":troop_no"),
        (store_skill_level, ":power", skl_necromancy, ":troop_no"),
        (val_mul,":power",5),
        (val_add,":power",":troop_level"),
        
        (try_begin),
          (ge, ":power", 60),
          (store_random_in_range, ":r", 0, 10),
          (assign,":number",1),
          (try_begin),
            (ge, ":r", 8),
            (assign,":spawn_troop_id","trp_fire_elemental_3"),
          (else_try),
            (ge, ":r", 6),
            (assign,":spawn_troop_id","trp_earth_elemental_3"),
          (else_try),
            (ge, ":r", 4),
            (assign,":spawn_troop_id","trp_water_elemental_3"),
          (else_try),
            (assign,":spawn_troop_id","trp_golem_4"),
            (assign,":number",2),
          (try_end),
        (else_try),
          (ge, ":power", 40),
          (store_random_in_range, ":r", 0, 10),
          (assign,":number",1),
          (try_begin),
            (ge, ":r", 8),
            (assign,":spawn_troop_id","trp_gargoyle"),
          (else_try),
            (ge, ":r", 6),
            (assign,":spawn_troop_id","trp_earth_elemental_2"),
          (else_try),
            (ge, ":r", 4),
            (assign,":spawn_troop_id","trp_fire_elemental_2"),
          (else_try),
            (assign,":spawn_troop_id","trp_water_elemental_2"),
          (try_end),
        (else_try),
          (ge, ":power", 20),
          (store_random_in_range, ":r", 0, 10),
          (assign,":number",1),
          (try_begin),
            (ge, ":r", 8),
            (assign,":spawn_troop_id","trp_air_elemental_2"),
          (else_try),
            (ge, ":r", 6),
            (assign,":spawn_troop_id","trp_water_elemental"),
          (else_try),
            (ge, ":r", 4),
            (assign,":spawn_troop_id","trp_mercenaries_end"),
            (assign,":number",2),
          (else_try),
            (assign,":spawn_troop_id","trp_golem_3"),
          (try_end),
        (else_try),
          (store_random_in_range, ":r", 0, 10),
          (assign,":number",1),
          (try_begin),
            (eq, ":r", 1),
            (assign,":spawn_troop_id","trp_air_elemental"),
          (else_try),
            (ge, ":r", 8),
            (assign,":spawn_troop_id","trp_golem_1"),
          (else_try),
            (ge, ":r", 6),
            (assign,":spawn_troop_id","trp_firefly"),
            (assign,":number",2),
          (else_try),
            (assign,":spawn_troop_id","trp_dragonfly"),
            (assign,":number",2),
          (try_end),
        (try_end),
        (gt,":spawn_troop_id",0),
        (gt,":number",0),
        (position_move_z,pos51,150),
        (position_move_y,pos51,150),
        (call_script,"script_cf_agent_spawn_agent_to_pos51", ":agent_summon", ":spawn_troop_id", ":number"),
      (else_try),#itm_voice_storm_call
        (eq, ":type", "itm_voice_storm_call"),
        (agent_play_sound,":shooter","snd_voice_storm_call"),
        (call_script, "script_cf_agent_voice_storm_call", ":shooter"),
        (call_script, "script_cf_agent_voice_storm_call", ":shooter"),
        (agent_set_slot, ":shooter", slot_agent_special_ability_affect_type, "itm_voice_storm_call"),
        (agent_set_slot, ":shooter", slot_agent_special_ability_affect_time, 30),
      (else_try),#itm_voice_call_dragon
        (eq, ":type", "itm_voice_call_dragon"),
        (agent_play_sound,":shooter","snd_voice_call_dragon"),
        
        (store_character_level,":troop_level",":troop_no"),
        (store_skill_level, ":power", skl_necromancy, ":troop_no"),
        (val_mul,":power",5),
        (val_add,":power",":troop_level"),
          
        (try_begin),
          (ge, ":power", 80),
          (assign,":time",5),
        (else_try),
          (ge, ":power", 60),
          (assign,":time",4),
        (else_try),
          (ge, ":power", 40),
          (assign,":time",3),
        (else_try),
          (ge, ":power", 20),
          (assign,":time",2),
        (else_try),
          (assign,":time",1),
        (try_end),
        (try_for_range,":unused",0,":time"),
          (store_random_in_range, ":ran", 0, 6),
          (try_begin),
            (eq,":ran",0),
            (assign,":spawn_troop_id","trp_red_dragon"),
          (else_try),  
            (eq,":ran",1),
            (assign,":spawn_troop_id","trp_black_dragon"),
          (else_try),  
            (eq,":ran",2),
            (assign,":spawn_troop_id","trp_green_dragon"),
          (else_try),  
            (eq,":ran",3),
            (assign,":spawn_troop_id","trp_gold_dragon"),
          (else_try),  
            (eq,":ran",4),
            (assign,":spawn_troop_id","trp_fire_dragon"),
          (else_try),  
            (eq,":ran",5),
            (assign,":spawn_troop_id","trp_lava_dragon"),
          (else_try),  
            (eq,":ran",6),
            (assign,":spawn_troop_id","trp_bone_dragon"),
          (else_try),  
            (eq,":ran",7),
            (assign,":spawn_troop_id","trp_ghost_dragon"),
          (else_try),  
            (eq,":ran",8),
            (assign,":spawn_troop_id","trp_lich_dragon"),
          (else_try),  
            (eq,":ran",9),
            (assign,":spawn_troop_id","trp_lizard_dragon"),
          (try_end),  
          (call_script,"script_cf_agent_spawn_agent_to_pos51", ":agent_summon", ":spawn_troop_id", 1),
        (try_end),  
      (else_try),#itm_voice_call_of_valor
        (eq, ":type", "itm_voice_call_of_valor"),
        (agent_play_sound,":shooter","snd_voice_call_of_valor"),
        (store_character_level,":troop_level",":troop_no"),
        (store_skill_level, ":power", skl_necromancy, ":troop_no"),
        (val_mul,":power",5),
        (val_add,":power",":troop_level"),
          
        (try_begin),
          (ge, ":power", 80),
          (assign,":time",5),
        (else_try),
          (ge, ":power", 60),
          (assign,":time",4),
        (else_try),
          (ge, ":power", 40),
          (assign,":time",3),
        (else_try),
          (ge, ":power", 20),
          (assign,":time",2),
        (else_try),
          (assign,":time",1),
        (try_end),
        (try_for_range,":unused",0,":time"),
          (eq, ":agent_gender", tf_male),
          (store_random_in_range, ":ran", 0, 5),
          (try_begin),
            (eq,":ran",0),
            (assign,":spawn_troop_id","trp_england_swordsman_3"),
          (else_try),  
            (eq,":ran",1),
            (assign,":spawn_troop_id","trp_teutonic_dis_knight"),
          (else_try),  
            (eq,":ran",2),
            (assign,":spawn_troop_id","trp_france_crossbow_4"),
          (else_try),  
            (eq,":ran",3),
            (assign,":spawn_troop_id","trp_iberian_town_footman_3"),
          (else_try),  
            (eq,":ran",4),
            (assign,":spawn_troop_id","trp_nord_valkyrie_3"),
          (try_end),  
          (call_script,"script_cf_agent_spawn_agent_to_pos51", ":agent_summon", ":spawn_troop_id", 1),
        (else_try),  
          (eq, ":agent_gender", tf_female),
          (store_random_in_range, ":ran", 0, 5),
          (try_begin),
            (eq,":ran",0),
            (assign,":spawn_troop_id","trp_sissofbattle_s"),
          (else_try),  
            (eq,":ran",1),
            (assign,":spawn_troop_id","trp_sissofbattle_r"),
          (else_try),  
            (eq,":ran",2),
            (assign,":spawn_troop_id","trp_france_crossbow_4"),
          (else_try),  
            (eq,":ran",3),
            (assign,":spawn_troop_id","trp_teutonic_dis_knight"),
          (else_try),  
            (eq,":ran",4),
            (assign,":spawn_troop_id","trp_nord_valkyrie_3"),
          (try_end),  
          (call_script,"script_cf_agent_spawn_agent_to_pos51", ":agent_summon", ":spawn_troop_id", 1),
        (else_try),  
          (eq, ":agent_gender", tf_male_elf),
          (store_random_in_range, ":ran", 0, 3),
          (try_begin),
            (eq,":ran",0),
            (assign,":spawn_troop_id","trp_woodelf_sworddancer"),
          (else_try),  
            (eq,":ran",1),
            (assign,":spawn_troop_id","trp_woodelf_sharpshooter"),
          (else_try),  
            (eq,":ran",2),
            (assign,":spawn_troop_id","trp_grandelf_arcane_guard"),
          (else_try),  
            (eq,":ran",3),
            (assign,":spawn_troop_id","trp_grandelf_guard"),
          (else_try),  
            (eq,":ran",4),
            (assign,":spawn_troop_id","trp_grandelf_mage_2"),
          (try_end),  
          (call_script,"script_cf_agent_spawn_agent_to_pos51", ":agent_summon", ":spawn_troop_id", 1),
        (else_try),  
          (this_or_next|eq, ":agent_gender", tf_beastman),
          (eq, ":agent_gender", tf_female_elf),
          (store_random_in_range, ":ran", 0, 5),
          (try_begin),
            (eq,":ran",0),
            (assign,":spawn_troop_id","trp_drowelf_assassin_3"),
          (else_try),  
            (eq,":ran",1),
            (assign,":spawn_troop_id","trp_drowelf_infantry_2"),
          (else_try),  
            (eq,":ran",2),
            (assign,":spawn_troop_id","trp_minotaur_3"),
          (else_try),  
            (eq,":ran",3),
            (assign,":spawn_troop_id","trp_drowelf_which_1"),
          (else_try),  
            (eq,":ran",4),
            (assign,":spawn_troop_id","trp_rat_5_3"),
          (try_end),  
          (call_script,"script_cf_agent_spawn_agent_to_pos51", ":agent_summon", ":spawn_troop_id", 1),
        (else_try),  
          (this_or_next|eq, ":agent_gender", tf_ogre),
          (eq, ":agent_gender", tf_orc),
          (store_random_in_range, ":ran", 0, 5),
          (try_begin),
            (eq,":ran",0),
            (assign,":spawn_troop_id","trp_orc_blackorc_boss"),
          (else_try),  
            (eq,":ran",1),
            (assign,":spawn_troop_id","trp_orc_big_boss"),
          (else_try),  
            (eq,":ran",2),
            (assign,":spawn_troop_id","trp_ogre_war"),
          (else_try),  
            (eq,":ran",3),
            (assign,":spawn_troop_id","trp_ogre_war2"),
          (else_try),  
            (eq,":ran",4),
            (assign,":spawn_troop_id","trp_ogre_mega"),
          (try_end),  
          (call_script,"script_cf_agent_spawn_agent_to_pos51", ":agent_summon", ":spawn_troop_id", 1),
        (else_try),  
          (eq, ":agent_gender", tf_dwarf),
          (store_random_in_range, ":ran", 0, 5),
          (try_begin),
            (eq,":ran",0),
            (assign,":spawn_troop_id","trp_dwarf_guard_3"),
          (else_try),  
            (eq,":ran",1),
            (assign,":spawn_troop_id","trp_dwarf_musketeer_3"),
          (else_try),  
            (eq,":ran",2),
            (assign,":spawn_troop_id","trp_dwarf_guard_1"),
          (else_try),  
            (eq,":ran",3),
            (assign,":spawn_troop_id","trp_nord_gunner"),
          (else_try),  
            (eq,":ran",4),
            (assign,":spawn_troop_id","trp_nord_halberd_2"),
          (try_end),  
          (call_script,"script_cf_agent_spawn_agent_to_pos51", ":agent_summon", ":spawn_troop_id", 1),
        (else_try),  
          (this_or_next|eq, ":agent_gender", tf_undead),
          (eq, ":agent_gender", tf_vampire),
          (store_random_in_range, ":ran", 0, 5),
          (try_begin),
            (eq,":ran",0),
            (assign,":spawn_troop_id","trp_lich_2"),
          (else_try),  
            (eq,":ran",1),
            (assign,":spawn_troop_id","trp_vampire_4"),
          (else_try),  
            (eq,":ran",2),
            (assign,":spawn_troop_id","trp_bone_dragon"),
          (else_try),  
            (eq,":ran",3),
            (assign,":spawn_troop_id","trp_mummy_3"),
          (else_try),  
            (eq,":ran",4),
            (assign,":spawn_troop_id","trp_undead_horse_3"),
          (try_end),  
          (call_script,"script_cf_agent_spawn_agent_to_pos51", ":agent_summon", ":spawn_troop_id", 1),
        (else_try),  
          (eq, ":agent_gender", tf_demon_human),
          (store_random_in_range, ":ran", 0, 6),
          (try_begin),
            (eq,":ran",0),
            (assign,":spawn_troop_id","trp_demon_human_5_1"),
          (else_try),  
            (eq,":ran",1),
            (assign,":spawn_troop_id","trp_demon_human_5_2"),
          (else_try),  
            (eq,":ran",2),
            (assign,":spawn_troop_id","trp_demon_7"),
          (else_try),  
            (eq,":ran",3),
            (assign,":spawn_troop_id","trp_demon_9"),
          (else_try),  
            (eq,":ran",4),
            (assign,":spawn_troop_id","trp_demon_magic_3"),
          (else_try),  
            (eq,":ran",5),
            (assign,":spawn_troop_id","trp_huge_inferno"),
          (try_end),  
          (call_script,"script_cf_agent_spawn_agent_to_pos51", ":agent_summon", ":spawn_troop_id", 1),
        (try_end),  
      (else_try),
        (eq, ":type", "itm_voice_disarm"),
        (agent_play_sound,":shooter","snd_voice_disarm"),
        (assign,":voice_type",1),
      (else_try),
        (eq, ":type", "itm_voice_dismaying_shout"),
        (agent_play_sound,":shooter","snd_voice_dismaying_shout"),
        (assign,":voice_type",2),
      (else_try),
        (eq, ":type", "itm_voice_bend_will"),
        (agent_play_sound,":shooter","snd_voice_bend_will"),
        (assign,":voice_type",1),
      (else_try),
        (eq, ":type", "itm_voice_fire_breath"),
        (agent_play_sound,":shooter","snd_voice_fire_breath"),
        (assign,":voice_type",1),
      (else_try),
        (eq, ":type", "itm_voice_frost_breath"),
        (agent_play_sound,":shooter","snd_voice_ice_form"),
        (assign,":voice_type",2),
      (else_try),
        (eq, ":type", "itm_voice_ice_form"),
        (agent_play_sound,":shooter","snd_voice_ice_form"),
        (assign,":voice_type",1),
      (else_try),
        (eq, ":type", "itm_voice_marked_for_death"),
        (agent_play_sound,":shooter","snd_voice_marked_for_death"),
        (assign,":voice_type",1),
      (else_try),
        (eq, ":type", "itm_voice_soul_tear"),
        (agent_play_sound,":shooter","snd_voice_soul_tear"),
        (assign,":voice_type",1),
      (else_try),
        (eq, ":type", "itm_voice_drain_vitality"),
        (agent_play_sound,":shooter","snd_voice_drain_vitality"),
        (assign,":voice_type",2),
      (try_end),
      
     (try_begin),
        (eq, ":type", -1),
        (store_random_in_range, ":type", 0, 4),
     (else_try),
       (eq, ":type", -1),
       (neg|troop_is_hero,":shooter"),
       (store_random_in_range, ":type", 0, 3),
     (try_end),
     
      (try_begin),
        (eq, ":type", 1),
        (agent_play_sound,":shooter","snd_cast_flame_burst"),
        (val_mul,":ch_bonus",4),
      (else_try),
        (eq, ":type", 3),
        (agent_play_sound,":shooter","snd_cast_warcry"),
        (val_mul,":ch_bonus",2),
      (else_try),
        (eq, ":type", 2),
        (agent_play_sound,":shooter","snd_cast_forst_ring"),
        (val_mul,":ch_bonus",2),
      (else_try),
        (agent_play_sound,":shooter","snd_cast_earth_shock"),
        (val_mul,":ch_bonus",3),
      (try_end),
      
      (store_mul, ":magic_power_bonus", 25, ":power"),
      (store_add, ":magic_power_factor", 100, ":magic_power_bonus"),
      (val_mul, ":ch_bonus", ":magic_power_factor"),  
      (val_div, ":ch_bonus", 100),
      
      (assign,":end_cound",11),
      (try_for_range,":POSY",0,":end_cound"),
        (eq, ":voice_type", 1),
        
        (copy_position,pos2,pos4),
        (val_mul,":POSY",150),
        (position_move_y,pos2,":POSY"),
        (val_div,":POSY",150),

        (position_set_z_to_ground_level, pos2),

        (agent_get_horse, ":target_horse", ":shooter"),
        (try_begin),
          (gt, ":target_horse", 0),
          (agent_set_position, ":target_horse", pos2),
        (else_try),
          (agent_set_position, ":shooter", pos2),
        (try_end),
        (copy_position,pos6,pos2),
        (position_move_z,pos6,100),
        
        (try_begin),
          (eq, ":type", "itm_voice_fire_breath"),
          (particle_system_burst,"psys_arrows_fire_small",pos6,3),
        (else_try),
          (eq, ":type", "itm_voice_ice_form"),
          (copy_position, pos30, pos6), 
          (position_move_z, pos30, 100),
          (particle_system_burst,"psys_Freezing_Trail",pos30,3),
        (else_try),
          (particle_system_burst, "psys_musket_smoke", pos6, 5),
        (try_end),
        (store_character_level,":troop_level",":troop_no"),
        #(assign,":kill",1),
        (try_for_agents,":agent"),
          (agent_is_alive,":agent"),
          (agent_is_human,":agent"),
          (this_or_next|agent_is_ally,":shooter"),
          (agent_is_ally,":agent"),
          (this_or_next|neg|agent_is_ally,":agent"),
          (neg|agent_is_ally,":shooter"),          

          (neq,":shooter",":agent"),
          (agent_get_position,pos3,":agent"),
          (position_set_z_to_ground_level, pos3),
          (get_distance_between_positions,":dist",pos2,pos3),
          (lt,":dist",150),
          (assign,":damage",":ch_bonus"),
          (agent_get_troop_id, ":inflicted_troop", ":agent"),
          (store_character_level,":inflicted_troop_level",":inflicted_troop"),
          
          (try_begin),
            (eq, ":type", "itm_voice_unrelenting_force"),
              (agent_set_animation, ":agent", "anim_voice_fly"),
              (copy_position, pos30, pos3), 
              (position_move_z, pos30, 200),
              (particle_system_burst, "psys_stun_effect", pos30, 1),
              (agent_set_slot, ":agent", slot_agent_special_ability_affect_type, dragon_voice),
              (agent_set_slot, ":agent", slot_agent_special_ability_affect_time, 2),
            (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", 0, 0, 0),
          (else_try),
            (eq, ":type", "itm_voice_disarm"),
            (try_begin),
              (neg|troop_is_hero,":inflicted_troop"),
              (gt,":troop_level",":inflicted_troop_level"),
              (lt,":inflicted_troop_level",30),
              
              (agent_get_wielded_item,":cur_weapon",":agent",0),
              (agent_get_wielded_item,":cur_sheld",":agent",1),
              (try_begin),
                (gt,":cur_weapon",0),
                (agent_unequip_item, ":agent", ":cur_weapon"),
              (try_end), 
              (try_begin),
                (gt,":cur_sheld",0),
                (agent_unequip_item, ":agent", ":cur_sheld"),
              (try_end), 
            (else_try),
              (agent_set_wielded_item, ":agent", -1),
            (try_end),
          (else_try),
            (eq, ":type", "itm_voice_bend_will"),
            (neg|troop_is_hero,":inflicted_troop"),
              (gt,":troop_level",":inflicted_troop_level"),
              (lt,":inflicted_troop_level",41),
            (store_random_in_range, ":r1", 0, 3),
            (eq, ":r1", 1),
            (agent_set_slot, ":agent", slot_agent_has_been_special_ability, charm),
            (agent_get_position, pos2, ":agent"),
            (position_move_z, pos2, 400),
            (particle_system_burst,"psys_charm_rose",pos2,35),
            (agent_get_team, ":agent_charm_team", ":shooter"),
            (agent_get_team, ":victim_team", ":agent"),
            (agent_set_team, ":agent", ":agent_charm_team"),
            (agent_set_slot, ":agent", slot_agent_old_team_set, ":victim_team"),
            (agent_set_slot, ":agent", slot_agent_charm_time, 15),
            (agent_force_rethink, ":agent"),
          (else_try),
            (eq, ":type", "itm_voice_fire_breath"),
            (agent_set_slot, ":agent", slot_agent_special_damage_type, severe_burn),
            (agent_set_slot, ":agent", slot_agent_special_damage_time, 1),
            (agent_set_slot, ":agent", slot_agent_special_damage_power, ":power"),
            (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", severe_burn, ":power", 15),
          (else_try),
            (eq, ":type", "itm_voice_ice_form"),
              (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", freeze, ":power", 15),
              (agent_set_slot, ":agent", slot_agent_special_damage_type, freeze),
              (agent_set_slot, ":agent", slot_agent_special_damage_time, 20),
              (agent_set_slot, ":agent", slot_agent_special_damage_power, 1),
          (else_try),
            (eq, ":type", "itm_voice_marked_for_death"),
            (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", marked_for_death, 5, 30),
            (agent_get_slot, ":special", ":agent", slot_agent_special_damage_type),
            (try_begin),
              (eq,":special", marked_for_death),
              (agent_get_slot, ":time", ":agent", slot_agent_special_damage_time),
              (gt, ":time", 0),
              (agent_get_slot, ":time", ":agent", slot_agent_special_damage_power),
              (val_add, ":time", 5),
              (agent_set_slot, ":agent", slot_agent_special_damage_power, ":time"),
            (else_try),
              (agent_set_slot, ":agent", slot_agent_special_damage_type, marked_for_death),
              (agent_set_slot, ":agent", slot_agent_special_damage_time, 30),
              (agent_set_slot, ":agent", slot_agent_special_damage_power, 5),
            (try_end),
          (else_try),
            (eq, ":type", "itm_voice_soul_tear"),
            (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", curse, 5, 5),

            (try_begin),
              (store_agent_hit_points, ":hp", ":agent"),
              (le, ":hp", 5),
              (copy_position, pos51, pos3),
              (store_random_in_range, ":spawn_troop_id", "trp_draugr_1", "trp_mummy_2_1"),
              (call_script,"script_cf_agent_spawn_agent_to_pos51", ":shooter", ":spawn_troop_id", 1),
            (try_end),
            (agent_get_slot, ":stamina", ":shooter", slot_agent_stamina),
            (val_add, ":stamina", 1),
            (agent_set_slot, ":shooter", slot_agent_stamina, ":stamina"),
            (store_agent_hit_points, ":hp", ":shooter"),
            (val_add, ":hp", 10),
            (agent_set_hit_points, ":shooter", ":hp"),
          (try_end),
          
        (try_end),
        (copy_position,pos5,pos4),#pos7    pos5
        (copy_position,pos6,pos4),
        (copy_position,pos7,pos4),#pos6    pos4
        
        (position_move_z,pos5,150),
        
        (position_move_y,pos6,100),
        
        (position_move_y,pos7,100),
        (position_move_z,pos7,150),
        (try_begin),
          (neg|position_has_line_of_sight_to_position, pos6, pos5),
          #(neg|position_has_line_of_sight_to_position, pos7, pos5),
          (neg|position_has_line_of_sight_to_position, pos6, pos4),
          (assign,":end_cound",0),
        (try_end),
      (try_end),
      
      
      (assign,":shell_burst",1),
      

      
      (try_for_range,":POSY",0,11),
        (this_or_next|eq, ":voice_type", 2),
        (is_between, ":type", 0, 4),
        
        (eq,":shell_burst",1),
        (copy_position,pos2,pos4),
        (val_mul,":POSY",160),
        (position_move_y,pos2,":POSY"),
        (val_div,":POSY",160),
        (try_begin), 
          (eq,":POSY",0),
          (assign,":begin",0),
          (assign,":end",0),
          (assign,":damage",0),
        (else_try),
          (is_between,":POSY",1,3),
          (assign,":begin",0),
          (assign,":end",1),
          (assign,":damage",":ch_bonus"),
          (val_mul,":damage",5),
          (val_div,":damage",2),
        (else_try),
          (is_between,":POSY",3,5),
          (assign,":begin",-1),
          (assign,":end",2),
          (assign,":damage",":ch_bonus"),
          (val_mul,":damage",4),
          (val_div,":damage",2),
        (else_try),
          (is_between,":POSY",5,7),
          (assign,":begin",-2),
          (assign,":end",3),
          (assign,":damage",":ch_bonus"),
          (val_mul,":damage",3),
          (val_div,":damage",2),
        (else_try),
          (is_between,":POSY",7,9),
          (assign,":begin",-3),
          (assign,":end",4),
          (assign,":damage",":ch_bonus"),
        (else_try),
          (is_between,":POSY",9,11),
          (assign,":begin",-4),
          (assign,":end",5),
          (assign,":damage",":ch_bonus"),
          (val_div,":damage",2),
        (try_end),
        
        (try_for_range,":POSX",":begin",":end"),
          (val_mul,":POSX",160),
          (position_move_x,pos2,":POSX"),
          (position_set_z_to_ground_level, pos2),
          
          (try_begin),
            (eq, ":type", 1),
            (particle_system_burst,"psys_arrows_fire_small",pos2,3),
          (else_try),
            (this_or_next|eq, ":type", "itm_voice_frost_breath"),
            (eq, ":type", 2),
            (copy_position, pos30, pos2), 
            (position_move_z, pos30, 100),
            (particle_system_burst,"psys_Freezing_Trail",pos30,3),
          (else_try),
            (copy_position, pos30, pos2), 
            (position_move_z, pos30, 50),
            (particle_system_burst, "psys_musket_smoke", pos30, 5),
          (try_end),

        

          (try_for_agents,":agent"),
            (agent_is_alive,":agent"),
            (this_or_next|agent_is_ally,":shooter"),
            (agent_is_ally,":agent"),
            (this_or_next|neg|agent_is_ally,":agent"),
            (neg|agent_is_ally,":shooter"),            
            (neq,":shooter",":agent"),
            (agent_get_position,pos3,":agent"),
            
          (try_begin),
            (eq, ":type", 3),
            (position_set_z_to_ground_level, pos3),
          (else_try),
            (eq, ":type", 0),
            (position_set_z_to_ground_level, pos3),
          (try_end),
          
            (get_distance_between_positions,":dist",pos2,pos3),
            (lt,":dist",150),
            
            
            (try_begin),
              (eq, ":type", "itm_voice_cyclone"),
                (agent_set_animation, ":agent", "anim_voice_fly"),
                (copy_position, pos30, pos3), 
                (position_move_z, pos30, 200),
                (particle_system_burst, "psys_stun_effect", pos30, 1),
                (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", power_jump, 0, 0),
                (agent_set_slot, ":agent", slot_agent_special_damage_type, power_jump),
                (agent_set_slot, ":agent", slot_agent_special_damage_power, 0),
                (agent_set_slot, ":agent", slot_agent_special_damage_time, 5),
            (else_try),
              (eq, ":type", "itm_voice_drain_vitality"),
            
              (store_agent_hit_points, ":hp", ":shooter"),
              (val_add, ":hp", 5),
              (agent_set_hit_points, ":shooter", ":hp"),
              
              (agent_get_slot, ":stamina", ":shooter", slot_agent_stamina),
              (val_add, ":stamina", 2),
              (agent_set_slot, ":shooter", slot_agent_stamina, ":stamina"),
              
              (agent_get_slot, ":stamina", ":shooter", slot_agent_mana),
              (val_add, ":stamina", 2),
              (agent_set_slot, ":shooter", slot_agent_mana, ":stamina"),
              
              (agent_set_slot, ":agent", slot_agent_special_ability_affect_type, Khorne_blessing),
              (agent_set_slot, ":agent", slot_agent_special_ability_affect_time, 10),
            (else_try),
              (eq, ":type", "itm_voice_frost_breath"),
              (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", ice, ":power", 15),
              (agent_set_slot, ":agent", slot_agent_special_damage_type, ice),
              (agent_set_slot, ":agent", slot_agent_special_damage_time, 10),
              (agent_set_slot, ":agent", slot_agent_special_damage_power, 5),
            (else_try),
              (eq, ":type", 1),
              (agent_set_slot, ":agent", slot_agent_special_damage_type, severe_burn),
              (agent_set_slot, ":agent", slot_agent_special_damage_time, 3),
              (agent_set_slot, ":agent", slot_agent_special_damage_power, ":power"),
              (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", severe_burn, ":power", 15),
            (else_try),
              (this_or_next|eq, ":type", "itm_voice_dismaying_shout"),
              (eq, ":type", 3),
              (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", 0, 0, 0),
              (agent_set_slot, ":agent", slot_agent_special_ability_affect_type, fright_aura),
              (agent_set_slot, ":agent", slot_agent_special_ability_affect_time, 30),
              (agent_get_troop_id, ":inflicted_troop", ":agent"),
              (neg|troop_is_hero,":inflicted_troop"),
              (store_skill_level, ":skill", "skl_magic_defence", ":inflicted_troop"),
              (store_sub,":defence",10,":skill"),
              (val_mul,":damage",":defence"),
              (val_div,":damage",10),
              (ge, ":damage", 0),
              (agent_get_slot, ":special", ":agent", slot_agent_special_ability_affect_type),
              (neg|eq,":special", berserk),
              (neg|eq,":special", stoneskin),
              (neg|eq,":special", holy_light),
              (agent_get_slot, ":agent_courage_score", ":agent",  slot_agent_courage_score),
              (store_mul, ":level", -100, ":damage"),
              #(val_mul, ":level", -1000),
              (val_add, ":agent_courage_score", ":level"),
              (agent_set_slot, ":agent", slot_agent_courage_score, ":agent_courage_score"),     
              (call_script, "script_decide_run_away_or_not", ":agent", 100),
            (else_try),
              (eq, ":type", 2),
              (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", freeze, ":power", 15),
              (agent_set_slot, ":agent", slot_agent_special_damage_type, freeze),
              (agent_set_slot, ":agent", slot_agent_special_damage_time, 20),
              (agent_set_slot, ":agent", slot_agent_special_damage_power, 1),
            (else_try),
              (try_begin),
                (agent_is_human,":agent"),
                (agent_set_animation, ":agent", "anim_voice_fly"),
                (copy_position, pos30, pos3), 
                (position_move_z, pos30, 200),
                (particle_system_burst, "psys_stun_effect", pos30, 1),
                (agent_set_slot, ":agent", slot_agent_special_ability_affect_type, dragon_voice),
                (agent_set_slot, ":agent", slot_agent_special_ability_affect_time, 5),

              (try_end),
              (call_script, "script_magic_deliver_damage_to_agent", ":shooter", ":agent", ":damage", 0, 0, 0),
            (try_end),
            (position_move_y,pos3,150),
          (try_end),
        (try_end),
      (try_end),
   ]),  

