    (0, 0, 0, [], [(eq, "$magic_click",1),
                   (eq, "$battle_click",0),
                   (start_presentation, "prsnt_magic"),]),
    (0, 0, 0, [], [(eq, "$magic_click",0),
                   (eq, "$battle_click",0),
                   (ge, "$mana",1),
                   (start_presentation, "prsnt_magic"),]),
    (0, 0, 0, [], [
        (key_clicked, key_e),
      (try_begin),
        (eq, "$choose_magic",0),
        (assign, "$choose_magic",1),
        (assign, "$choose_magic_begin",1),
      (else_try),
        (eq, "$choose_magic",1),
        (assign, "$choose_magic",0),
        (assign, "$choose_magic_begin",0),
        (assign,"$magic_will_choose",0),
      (try_end),]),
    (0, 0, 0, [], [(eq, "$choose_magic",1),
        (key_clicked, key_left_mouse_button),
        (troop_set_slot,"trp_player",slot_troop_Magic_Choose,"$magic_will_choose"),
        (assign, "$choose_magic",0),
        (assign, "$choose_magic_begin",0),
        (assign,"$right_mouse_button_is_down", 1),]),








  ("magic", prsntf_read_only, 0, [
      (ti_on_presentation_load,
       [(call_script, "script_magic_load"),

        (assign, "$magic_click",1),
        (assign, "$battle_click",1),
        (presentation_set_duration, 999999),
        ]),
        
      (ti_on_presentation_run,
       [
       
       (store_trigger_param_1, ":cur_time"),

       (gt, ":cur_time", 200),
     (try_begin),
       (game_key_clicked, gk_view_orders),
       (assign, "$magic_click",0),
       (presentation_set_duration, 0),
     (else_try),
       (eq, "$mana",0),
        (assign, "$magic_click",0),
        (assign, "$battle_click",0),
       (presentation_set_duration, 0),
     (try_end),
        ]),
        
      (ti_on_presentation_run,
       [(call_script, "script_magic_run"),]),
       
      (ti_on_presentation_run,
       [(set_fixed_point_multiplier, 1000),
        (try_begin),
        (try_begin),
          (eq, "$choose_magic_begin",1),
          (call_script, "script_choose_spells_begin"),
        (try_end),
          (eq, "$choose_magic",1),
          (key_clicked, key_t),
          (call_script, "script_choose_spells"),
        (else_try),
          (eq, "$choose_magic",0),
          (eq, "$choose_magic_begin",0),
          (overlay_set_alpha, "$magic_icon1", 0x00),
          (overlay_set_alpha, "$magic_icon2", 0x00),
          (overlay_set_alpha, "$magic_icon3", 0x00),
          (overlay_set_alpha, "$magic_icon4", 0x00),
          (overlay_set_alpha, "$magic_icon5", 0x00),
          (overlay_set_alpha, "$magic_icon6", 0x00),
          (overlay_set_alpha, "$magic_icon7", 0x00),
          (overlay_set_alpha, "$magic_icon8", 0x00),
          (overlay_set_alpha, "$magic_icon9", 0x00),
          (overlay_set_alpha, "$magic_icon10", 0x00),
          (overlay_set_alpha, "$magic_icon11", 0x00),
          (overlay_set_alpha, "$magic_icon12", 0x00),
          (overlay_set_alpha, "$magic_icon13", 0x00),
          (overlay_set_alpha, "$magic_icon14", 0x00),
          (overlay_set_alpha, "$magic_icon15", 0x00),
          (overlay_set_alpha, "$magic_icon16", 0x00),
          (overlay_set_alpha, "$magic_icon17", 0x00),
          (overlay_set_alpha, "$magic_icon18", 0x00),
          (overlay_set_alpha, "$magic_choose", 0x00),
        (try_end),


          
          ]),

      ]),



  ("magic_load",
   [    (set_fixed_point_multiplier, 1000),
        (create_mesh_overlay, "$magic", "mesh_magic"),
        (create_mesh_overlay, "$magic_1_1", "mesh_magic_1_1"),
        (create_mesh_overlay, "$magic_1_2", "mesh_magic_1_2"),
        (create_mesh_overlay, "$magic_1_3", "mesh_magic_1_3"),
        (create_mesh_overlay, "$magic_2_1", "mesh_magic_2_1"),
        (create_mesh_overlay, "$magic_2_2", "mesh_magic_2_2"),
        (create_mesh_overlay, "$magic_2_3", "mesh_magic_2_3"),
        (create_mesh_overlay, "$magic_3", "mesh_magic_3"),
        (create_mesh_overlay, "$magic_4_1", "mesh_magic_4_1"),
        (create_mesh_overlay, "$magic_4_2", "mesh_magic_4_2"),
        (create_mesh_overlay, "$magic_5", "mesh_magic_5"),
        (create_mesh_overlay, "$magic_6_1", "mesh_magic_6_1"),
        (create_mesh_overlay, "$magic_6_2", "mesh_magic_6_2"),
        (create_mesh_overlay, "$magic_6_3", "mesh_magic_6_3"),
        (create_mesh_overlay, "$magic_7", "mesh_magic_7"),
        (create_mesh_overlay, "$magic_8_1", "mesh_magic_8_1"),
        (create_mesh_overlay, "$magic_8_2", "mesh_magic_8_2"),
        (create_mesh_overlay, "$magic_9", "mesh_magic_9"),
        (create_mesh_overlay, "$magic_10_1", "mesh_magic_10_1"),
        (create_mesh_overlay, "$magic_10_2", "mesh_magic_10_2"),
        (create_mesh_overlay, "$magic_10_3", "mesh_magic_10_3"),
        (create_mesh_overlay, "$magic_10_4", "mesh_magic_10_4"),
        (create_mesh_overlay, "$magic_11", "mesh_magic_11"),
        (create_mesh_overlay, "$magic_12", "mesh_magic_12"),
        (create_mesh_overlay, "$magic_13", "mesh_magic_13"),
        (create_mesh_overlay, "$magic_14", "mesh_magic_14"),
        (create_mesh_overlay, "$magic_15", "mesh_magic_15"),
        (create_mesh_overlay, "$magic_16", "mesh_magic_16"),
        (create_mesh_overlay, "$magic_17_1", "mesh_magic_17_1"),
        (create_mesh_overlay, "$magic_17_2", "mesh_magic_17_2"),
        (create_mesh_overlay, "$magic_18", "mesh_magic_18"),
        (create_mesh_overlay, "$magic_icon1", "mesh_magic1"),
        (create_mesh_overlay, "$magic_icon2", "mesh_magic2"),
        (create_mesh_overlay, "$magic_icon3", "mesh_magic3"),
        (create_mesh_overlay, "$magic_icon4", "mesh_magic4"),
        (create_mesh_overlay, "$magic_icon5", "mesh_magic5"),
        (create_mesh_overlay, "$magic_icon6", "mesh_magic6"),
        (create_mesh_overlay, "$magic_icon7", "mesh_magic7"),
        (create_mesh_overlay, "$magic_icon8", "mesh_magic8"),
        (create_mesh_overlay, "$magic_icon9", "mesh_magic9"),
        (create_mesh_overlay, "$magic_icon10", "mesh_magic10"),
        (create_mesh_overlay, "$magic_icon11", "mesh_magic11"),
        (create_mesh_overlay, "$magic_icon12", "mesh_magic12"),
        (create_mesh_overlay, "$magic_icon13", "mesh_magic13"),
        (create_mesh_overlay, "$magic_icon14", "mesh_magic14"),
        (create_mesh_overlay, "$magic_icon15", "mesh_magic15"),
        (create_mesh_overlay, "$magic_icon16", "mesh_magic16"),
        (create_mesh_overlay, "$magic_icon17", "mesh_magic17"),
        (create_mesh_overlay, "$magic_icon18", "mesh_magic18"),
        (create_mesh_overlay, "$magic_choose", "mesh_magic_choose"),
        
        
        
        (position_set_x,pos1,3300),
        (position_set_y,pos1,2000),
        (overlay_set_size, "$magic", pos1),
        (overlay_set_size, "$magic_1_1", pos1),
        (overlay_set_size, "$magic_1_2", pos1),
        (overlay_set_size, "$magic_1_3", pos1),
        (overlay_set_size, "$magic_2_1", pos1),
        (overlay_set_size, "$magic_2_2", pos1),
        (overlay_set_size, "$magic_2_3", pos1),
        (overlay_set_size, "$magic_3", pos1),
        (overlay_set_size, "$magic_4_1", pos1),
        (overlay_set_size, "$magic_4_2", pos1),
        (overlay_set_size, "$magic_5", pos1),
        (overlay_set_size, "$magic_6_1", pos1),
        (overlay_set_size, "$magic_6_2", pos1),
        (overlay_set_size, "$magic_6_3", pos1),
        (overlay_set_size, "$magic_7", pos1),
        (overlay_set_size, "$magic_8_1", pos1),
        (overlay_set_size, "$magic_8_2", pos1),
        (overlay_set_size, "$magic_9", pos1),
        (overlay_set_size, "$magic_10_1", pos1),
        (overlay_set_size, "$magic_10_2", pos1),
        (overlay_set_size, "$magic_10_3", pos1),
        (overlay_set_size, "$magic_10_4", pos1),
        (overlay_set_size, "$magic_11", pos1),
        (overlay_set_size, "$magic_12", pos1),
        (overlay_set_size, "$magic_13", pos1),
        (overlay_set_size, "$magic_14", pos1),
        (overlay_set_size, "$magic_15", pos1),
        (overlay_set_size, "$magic_16", pos1),
        (overlay_set_size, "$magic_17_1", pos1),
        (overlay_set_size, "$magic_17_2", pos1),
        (overlay_set_size, "$magic_18", pos1),
        (position_set_x,pos1,1300),
        (position_set_y,pos1,1300),
        (overlay_set_size, "$magic_icon1", pos1),
        (overlay_set_size, "$magic_icon2", pos1),
        (overlay_set_size, "$magic_icon3", pos1),
        (overlay_set_size, "$magic_icon4", pos1),
        (overlay_set_size, "$magic_icon5", pos1),
        (overlay_set_size, "$magic_icon6", pos1),
        (overlay_set_size, "$magic_icon7", pos1),
        (overlay_set_size, "$magic_icon8", pos1),
        (overlay_set_size, "$magic_icon9", pos1),
        (overlay_set_size, "$magic_icon10", pos1),
        (overlay_set_size, "$magic_icon11", pos1),
        (overlay_set_size, "$magic_icon12", pos1),
        (overlay_set_size, "$magic_icon13", pos1),
        (overlay_set_size, "$magic_icon14", pos1),
        (overlay_set_size, "$magic_icon15", pos1),
        (overlay_set_size, "$magic_icon16", pos1),
        (overlay_set_size, "$magic_icon17", pos1),
        (overlay_set_size, "$magic_icon18", pos1),

        (overlay_set_size, "$magic_choose", pos1),
        
        (overlay_set_alpha, "$magic_icon1", 0x00),
        (overlay_set_alpha, "$magic_icon2", 0x00),
        (overlay_set_alpha, "$magic_icon3", 0x00),
        (overlay_set_alpha, "$magic_icon4", 0x00),
        (overlay_set_alpha, "$magic_icon5", 0x00),
        (overlay_set_alpha, "$magic_icon6", 0x00),
        (overlay_set_alpha, "$magic_icon7", 0x00),
        (overlay_set_alpha, "$magic_icon8", 0x00),
        (overlay_set_alpha, "$magic_icon9", 0x00),
        (overlay_set_alpha, "$magic_icon10", 0x00),
        (overlay_set_alpha, "$magic_icon11", 0x00),
        (overlay_set_alpha, "$magic_icon12", 0x00),
        (overlay_set_alpha, "$magic_icon13", 0x00),
        (overlay_set_alpha, "$magic_icon14", 0x00),
        (overlay_set_alpha, "$magic_icon15", 0x00),
        (overlay_set_alpha, "$magic_icon16", 0x00),
        (overlay_set_alpha, "$magic_icon17", 0x00),
        (overlay_set_alpha, "$magic_icon18", 0x00),
        (overlay_set_alpha, "$magic_choose", 0x00),
        (overlay_set_alpha, "$magic", 0x00),
        (overlay_set_alpha, "$magic_1_1", 0x00),
        (overlay_set_alpha, "$magic_1_2", 0x00),
        (overlay_set_alpha, "$magic_1_3", 0x00),
        (overlay_set_alpha, "$magic_2_1", 0x00),
        (overlay_set_alpha, "$magic_2_2", 0x00),
        (overlay_set_alpha, "$magic_2_3", 0x00),
        (overlay_set_alpha, "$magic_3", 0x00),
        (overlay_set_alpha, "$magic_4_1", 0x00),
        (overlay_set_alpha, "$magic_4_2", 0x00),
        (overlay_set_alpha, "$magic_5", 0x00),
        (overlay_set_alpha, "$magic_6_1", 0x00),
        (overlay_set_alpha, "$magic_6_2", 0x00),
        (overlay_set_alpha, "$magic_6_3", 0x00),
        (overlay_set_alpha, "$magic_7", 0x00),
        (overlay_set_alpha, "$magic_8_1", 0x00),
        (overlay_set_alpha, "$magic_8_2", 0x00),
        (overlay_set_alpha, "$magic_9", 0x00),
        (overlay_set_alpha, "$magic_10_1", 0x00),
        (overlay_set_alpha, "$magic_10_2", 0x00),
        (overlay_set_alpha, "$magic_10_3", 0x00),
        (overlay_set_alpha, "$magic_10_4", 0x00),
        (overlay_set_alpha, "$magic_11", 0x00),
        (overlay_set_alpha, "$magic_12", 0x00),
        (overlay_set_alpha, "$magic_13", 0x00),
        (overlay_set_alpha, "$magic_14", 0x00),
        (overlay_set_alpha, "$magic_15", 0x00),
        (overlay_set_alpha, "$magic_16", 0x00),
        (overlay_set_alpha, "$magic_17_1", 0x00),
        (overlay_set_alpha, "$magic_17_2", 0x00),
        (overlay_set_alpha, "$magic_18", 0x00),

        
        (position_set_x,pos1,150),
        (position_set_y,pos1,40),
        (overlay_set_position, "$magic", pos1),
        (overlay_set_position, "$magic_1_1", pos1),
        (overlay_set_position, "$magic_1_2", pos1),
        (overlay_set_position, "$magic_1_3", pos1),
        (overlay_set_position, "$magic_2_1", pos1),
        (overlay_set_position, "$magic_2_2", pos1),
        (overlay_set_position, "$magic_2_3", pos1),
        (overlay_set_position, "$magic_3", pos1),
        (overlay_set_position, "$magic_4_1", pos1),
        (overlay_set_position, "$magic_4_2", pos1),
        (overlay_set_position, "$magic_5", pos1),
        (overlay_set_position, "$magic_6_1", pos1),
        (overlay_set_position, "$magic_6_2", pos1),
        (overlay_set_position, "$magic_6_3", pos1),
        (overlay_set_position, "$magic_7", pos1),
        (overlay_set_position, "$magic_8_1", pos1),
        (overlay_set_position, "$magic_8_2", pos1),
        (overlay_set_position, "$magic_9", pos1),
        (overlay_set_position, "$magic_10_1", pos1),
        (overlay_set_position, "$magic_10_2", pos1),
        (overlay_set_position, "$magic_10_3", pos1),
        (overlay_set_position, "$magic_10_4", pos1),
        (overlay_set_position, "$magic_11", pos1),
        (overlay_set_position, "$magic_12", pos1),
        (overlay_set_position, "$magic_13", pos1),
        (overlay_set_position, "$magic_14", pos1),
        (overlay_set_position, "$magic_15", pos1),
        (overlay_set_position, "$magic_16", pos1),
        (overlay_set_position, "$magic_17_1", pos1),
        (overlay_set_position, "$magic_17_2", pos1),
        (overlay_set_position, "$magic_18", pos1),

       ]),
  ("magic_run",
   [    (set_fixed_point_multiplier, 1000),
        (overlay_set_alpha, "$magic", 0x00),
        (overlay_set_alpha, "$magic_1_1", 0x00),
        (overlay_set_alpha, "$magic_1_2", 0x00),
        (overlay_set_alpha, "$magic_1_3", 0x00),
        (overlay_set_alpha, "$magic_2_1", 0x00),
        (overlay_set_alpha, "$magic_2_2", 0x00),
        (overlay_set_alpha, "$magic_2_3", 0x00),
        (overlay_set_alpha, "$magic_3", 0x00),
        (overlay_set_alpha, "$magic_4_1", 0x00),
        (overlay_set_alpha, "$magic_4_2", 0x00),
        (overlay_set_alpha, "$magic_5", 0x00),
        (overlay_set_alpha, "$magic_6_1", 0x00),
        (overlay_set_alpha, "$magic_6_2", 0x00),
        (overlay_set_alpha, "$magic_6_3", 0x00),
        (overlay_set_alpha, "$magic_7", 0x00),
        (overlay_set_alpha, "$magic_8_1", 0x00),
        (overlay_set_alpha, "$magic_8_2", 0x00),
        (overlay_set_alpha, "$magic_9", 0x00),
        (overlay_set_alpha, "$magic_10_1", 0x00),
        (overlay_set_alpha, "$magic_10_2", 0x00),
        (overlay_set_alpha, "$magic_10_3", 0x00),
        (overlay_set_alpha, "$magic_10_4", 0x00),
        (overlay_set_alpha, "$magic_11", 0x00),
        (overlay_set_alpha, "$magic_12", 0x00),
        (overlay_set_alpha, "$magic_13", 0x00),
        (overlay_set_alpha, "$magic_14", 0x00),
        (overlay_set_alpha, "$magic_15", 0x00),
        (overlay_set_alpha, "$magic_16", 0x00),
        (overlay_set_alpha, "$magic_17_1", 0x00),
        (overlay_set_alpha, "$magic_17_2", 0x00),
        (overlay_set_alpha, "$magic_18", 0x00),
   (try_begin),
        (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Fireball),
        (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Searing_Ray),
       (try_begin),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Novice_Fireball),
         (overlay_set_alpha, "$magic_1_1", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Journeyman_Fireball),
         (overlay_set_alpha, "$magic_1_2", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Fireball),
         (overlay_set_alpha, "$magic_1_3", 0xff),
       (try_end),
   (else_try),
        (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Searing_Ray),
        (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Burning_Trail),
       (try_begin),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Novice_Searing_Ray),
         (overlay_set_alpha, "$magic_2_1", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Journeyman_Searing_Ray),
         (overlay_set_alpha, "$magic_2_2", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Searing_Ray),
         (overlay_set_alpha, "$magic_2_3", 0xff),
       (try_end),
   (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Burning_Trail),
        (overlay_set_alpha, "$magic_3", 0xff),
   (else_try),
        (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Wall_of_Fire),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Wall_of_Fire),
       (try_begin),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Wall_of_Fire),
         (overlay_set_alpha, "$magic_4_1", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Wall_of_Fire),
         (overlay_set_alpha, "$magic_4_2", 0xff),
       (try_end),
   (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Fire_Shroud),
        (overlay_set_alpha, "$magic_5", 0xff),
   (else_try),
        (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Wave),
        (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Freezing_Trail),
       (try_begin),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Novice_Wave),
         (overlay_set_alpha, "$magic_6_1", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Journeyman_Wave),
         (overlay_set_alpha, "$magic_6_2", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Wave),
         (overlay_set_alpha, "$magic_6_3", 0xff),
       (try_end),
   (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Freezing_Trail),
        (overlay_set_alpha, "$magic_7", 0xff),
   (else_try),
        (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Ice_Storm),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Ice_Storm),
       (try_begin),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Ice_Storm),
         (overlay_set_alpha, "$magic_8_1", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Ice_Storm),
         (overlay_set_alpha, "$magic_8_2", 0xff),
       (try_end),
   (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Tsunami),
        (overlay_set_alpha, "$magic_9", 0xff),
   (else_try),
        (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Cure),
        (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Cats_grace),
       (try_begin),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Novice_Cure),
         (overlay_set_alpha, "$magic_10_1", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Journeyman_Cure),
         (overlay_set_alpha, "$magic_10_2", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Cure),
         (overlay_set_alpha, "$magic_10_3", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Cure_Others),
         (overlay_set_alpha, "$magic_10_4", 0xff),
       (try_end),
       (try_begin),
         (key_clicked,key_left_control),
       (try_begin),
         (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Novice_Cure),
         (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Journeyman_Cure),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Cure),
         (troop_set_slot,"trp_player",slot_troop_Magic_Choose,magic_Cure_Others),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Cure_Others),
        (try_begin),
          (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
          (troop_set_slot,"trp_player",slot_troop_Magic_Choose,magic_Novice_Cure),
        (else_try),
          (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
          (troop_set_slot,"trp_player",slot_troop_Magic_Choose,magic_Journeyman_Cure),
        (else_try),
          (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
          (troop_set_slot,"trp_player",slot_troop_Magic_Choose,magic_Master_Cure),
        (try_end),
       (try_end),
       (try_end),
   (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Ammunition_Restoration),
        (overlay_set_alpha, "$magic_14", 0xff),
   (try_end),
   (try_begin),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Cats_grace),
        (overlay_set_alpha, "$magic_11", 0xff),
   (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Bulls_strength),
        (overlay_set_alpha, "$magic_12", 0xff),
   (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Mass_Cure),
        (overlay_set_alpha, "$magic_13", 0xff),
   (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Summon_Undead),
        (overlay_set_alpha, "$magic_15", 0xff),
   (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Teleport),
        (overlay_set_alpha, "$magic_16", 0xff),
   (else_try),
        (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Sandstorm),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Sandstorm),
       (try_begin),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Sandstorm),
         (overlay_set_alpha, "$magic_17_1", 0xff),
       (else_try),
         (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Sandstorm),
         (overlay_set_alpha, "$magic_17_2", 0xff),
       (try_end),
   (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Mind_Fog),
        (overlay_set_alpha, "$magic_18", 0xff),
   (else_try),
        (overlay_set_alpha, "$magic", 0xff),
   (try_end),
    ]),
  ("choose_spells",
   [        (position_set_x,pos1,120),
            (position_set_y,pos1,120),
            (position_set_x,pos2,200),
            (position_set_y,pos2,120),
            (position_set_x,pos3,280),
            (position_set_y,pos3,120),
            (position_set_x,pos4,360),
            (position_set_y,pos4,120),
            (position_set_x,pos5,440),
            (position_set_y,pos5,120),
            (position_set_x,pos6,520),
            (position_set_y,pos6,120),
            (try_begin),
                (troop_slot_eq,"trp_player",slot_troop_Magic_Type,magic_fire_skills),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Fireball,magic_Novice),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Searing_Ray,magic_Novice),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Burning_Trail,magic_Novice),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Wall_of_Fire,magic_Novice),
                (troop_slot_ge,"trp_player",slot_troop_Fire_Shroud,magic_Novice),
              (try_begin),
                  (this_or_next|eq, "$magic_will_choose", magic_Novice_Fireball),
                  (this_or_next|eq, "$magic_will_choose", magic_Journeyman_Fireball),
                  (eq, "$magic_will_choose", magic_Master_Fireball),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Searing_Ray,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Searing_Ray,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Searing_Ray),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Searing_Ray,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Searing_Ray),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Searing_Ray,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Searing_Ray),
                  (try_end),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
                (try_end),
              (else_try),
                  (this_or_next|eq, "$magic_will_choose", magic_Novice_Searing_Ray),
                  (this_or_next|eq, "$magic_will_choose", magic_Journeyman_Searing_Ray),
                  (eq, "$magic_will_choose", magic_Master_Searing_Ray),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Burning_Trail,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos3"),
                  (assign, "$magic_will_choose", magic_Burning_Trail),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
                (try_end),
              (else_try),
                  (eq, "$magic_will_choose", magic_Burning_Trail),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Wall_of_Fire,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos4"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wall_of_Fire,magic_Learned),
                    (assign, "$magic_will_choose", magic_Wall_of_Fire),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wall_of_Fire,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wall_of_Fire),
                  (try_end),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Fire_Shroud,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos5"),
                  (assign, "$magic_will_choose", magic_Fire_Shroud),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
                (try_end),
              (else_try),
                  (this_or_next|eq, "$magic_will_choose", magic_Wall_of_Fire),
                  (eq, "$magic_will_choose", magic_Master_Wall_of_Fire),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Fire_Shroud,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos5"),
                  (assign, "$magic_will_choose", magic_Fire_Shroud),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
                (try_end),
              (else_try),
                  (eq, "$magic_will_choose", magic_Fire_Shroud),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
              (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Fireball),
                  (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Searing_Ray),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Searing_Ray,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Searing_Ray,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Searing_Ray),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Searing_Ray,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Searing_Ray),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Searing_Ray,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Searing_Ray),
                  (try_end),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Searing_Ray),
                  (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Burning_Trail),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Burning_Trail,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos3"),
                  (assign, "$magic_will_choose", magic_Burning_Trail),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Burning_Trail),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Wall_of_Fire,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos4"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wall_of_Fire,magic_Learned),
                    (assign, "$magic_will_choose", magic_Wall_of_Fire),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wall_of_Fire,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wall_of_Fire),
                  (try_end),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
                (try_end),
              (else_try),
                  (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Wall_of_Fire),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Wall_of_Fire),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Fire_Shroud,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos5"),
                  (assign, "$magic_will_choose", magic_Fire_Shroud),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Fire_Shroud),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
              (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Fireball),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Fireball),
                  (try_end),
              (try_end),
            (else_try),
                (troop_slot_eq,"trp_player",slot_troop_Magic_Type,magic_cold_skills),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Wave,magic_Novice),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Freezing_Trail,magic_Novice),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Ice_Storm,magic_Novice),
                (troop_slot_ge,"trp_player",slot_troop_Tsunami,magic_Novice),
              (try_begin),
                  (this_or_next|eq, "$magic_will_choose", magic_Novice_Wave),
                  (this_or_next|eq, "$magic_will_choose", magic_Journeyman_Wave),
                  (eq, "$magic_will_choose", magic_Master_Wave),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Freezing_Trail,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (assign, "$magic_will_choose", magic_Freezing_Trail),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wave),
                  (try_end),
                (try_end),
              (else_try),
                  (eq, "$magic_will_choose", magic_Freezing_Trail),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Ice_Storm,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos3"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Ice_Storm,magic_Learned),
                    (assign, "$magic_will_choose", magic_Ice_Storm),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Ice_Storm,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Ice_Storm),
                  (try_end),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Tsunami,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos4"),
                  (assign, "$magic_will_choose", magic_Tsunami),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wave),
                  (try_end),
                (try_end),
              (else_try),
                  (this_or_next|eq, "$magic_will_choose", magic_Ice_Storm),
                  (eq, "$magic_will_choose", magic_Master_Ice_Storm),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Tsunami,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos4"),
                  (assign, "$magic_will_choose", magic_Tsunami),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wave),
                  (try_end),
                (try_end),
              (else_try),
                  (eq, "$magic_will_choose", magic_Tsunami),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wave),
                  (try_end),
              (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Wave),
                  (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Freezing_Trail),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Freezing_Trail,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (assign, "$magic_will_choose", magic_Freezing_Trail),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wave),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Freezing_Trail),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Ice_Storm,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos3"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Ice_Storm,magic_Learned),
                    (assign, "$magic_will_choose", magic_Ice_Storm),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Ice_Storm,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Ice_Storm),
                  (try_end),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Tsunami,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos4"),
                  (assign, "$magic_will_choose", magic_Tsunami),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wave),
                  (try_end),
                (try_end),
              (else_try),
                  (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Ice_Storm),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Ice_Storm),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Tsunami,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos4"),
                  (assign, "$magic_will_choose", magic_Tsunami),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wave),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Tsunami),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wave),
                  (try_end),
              (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Wave),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Wave),
                  (try_end),
              (try_end),
            (else_try),
                (troop_slot_eq,"trp_player",slot_troop_Magic_Type,magic_auxiliary_spells),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Cure,magic_Novice),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Cats_grace,magic_Novice),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Bulls_strength,magic_Novice),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Mass_Cure,magic_Novice),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Ammunition_Restoration,magic_Novice),
                (troop_slot_ge,"trp_player",slot_troop_Mind_Fog,magic_Novice),
              (try_begin),
                  (this_or_next|eq, "$magic_will_choose", magic_Novice_Cure),
                  (this_or_next|eq, "$magic_will_choose", magic_Journeyman_Cure),
                  (eq, "$magic_will_choose", magic_Master_Cure),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Ammunition_Restoration,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (assign, "$magic_will_choose", magic_Ammunition_Restoration),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Cats_grace,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos3"),
                  (assign, "$magic_will_choose", magic_Cats_grace),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
                (try_end),
              (else_try),
                  (eq, "$magic_will_choose", magic_Ammunition_Restoration),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Cats_grace,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos3"),
                  (assign, "$magic_will_choose", magic_Cats_grace),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
                (try_end),
              (else_try),
                  (eq, "$magic_will_choose", magic_Cats_grace),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Bulls_strength,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos4"),
                  (assign, "$magic_will_choose", magic_Bulls_strength),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Mass_Cure,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos5"),
                  (assign, "$magic_will_choose", magic_Mass_Cure),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Mind_Fog,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos6"),
                  (assign, "$magic_will_choose", magic_Mind_Fog),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
                (try_end),
              (else_try),
                  (eq, "$magic_will_choose", magic_Bulls_strength),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Mass_Cure,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos5"),
                  (assign, "$magic_will_choose", magic_Mass_Cure),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Mind_Fog,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos6"),
                  (assign, "$magic_will_choose", magic_Mind_Fog),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
                (try_end),
              (else_try),
                  (eq, "$magic_will_choose", magic_Mass_Cure),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Mind_Fog,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos6"),
                  (assign, "$magic_will_choose", magic_Mind_Fog),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
                (try_end),
              (else_try),
                  (eq, "$magic_will_choose", magic_Mind_Fog),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
              (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Cure),
                  (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Cats_grace),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Ammunition_Restoration,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (assign, "$magic_will_choose", magic_Ammunition_Restoration),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Cats_grace,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos3"),
                  (assign, "$magic_will_choose", magic_Cats_grace),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Ammunition_Restoration),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Cats_grace,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos3"),
                  (assign, "$magic_will_choose", magic_Cats_grace),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Cats_grace),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Bulls_strength,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos4"),
                  (assign, "$magic_will_choose", magic_Bulls_strength),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Mass_Cure,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos5"),
                  (assign, "$magic_will_choose", magic_Mass_Cure),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Mind_Fog,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos6"),
                  (assign, "$magic_will_choose", magic_Cats_grace),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Bulls_strength),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Mass_Cure,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos5"),
                  (assign, "$magic_will_choose", magic_Mass_Cure),
                (else_try),
                  (troop_slot_ge,"trp_player",slot_troop_Mind_Fog,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos6"),
                  (assign, "$magic_will_choose", magic_Cats_grace),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Mass_Cure),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Mind_Fog,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos6"),
                  (assign, "$magic_will_choose", magic_Cats_grace),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Mind_Fog),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
              (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
                    (assign, "$magic_will_choose", magic_Novice_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
                    (assign, "$magic_will_choose", magic_Journeyman_Cure),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Cure),
                  (try_end),
              (try_end),
            (else_try),
                (troop_slot_eq,"trp_player",slot_troop_Magic_Type,magic_awaken_skills),
                (troop_slot_ge,"trp_player",slot_troop_Summon_Undead,magic_Novice),
                (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                (assign, "$magic_will_choose", magic_Summon_Undead),
            (else_try),
                (troop_slot_eq,"trp_player",slot_troop_Magic_Type,magic_other_skills),
                (this_or_next|troop_slot_ge,"trp_player",slot_troop_Teleport,magic_Novice),
                (troop_slot_ge,"trp_player",slot_troop_Sandstorm,magic_Novice),
              (try_begin),
                  (eq, "$magic_will_choose", magic_Teleport),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Sandstorm,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Sandstorm,magic_Learned),
                    (assign, "$magic_will_choose", magic_Sandstorm),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Sandstorm,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Sandstorm),
                  (try_end),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (assign, "$magic_will_choose", magic_Teleport),
                (try_end),
              (else_try),
                  (this_or_next|eq, "$magic_will_choose", magic_Sandstorm),
                  (eq, "$magic_will_choose", magic_Master_Sandstorm),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Teleport,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (assign, "$magic_will_choose", magic_Teleport),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Sandstorm,magic_Learned),
                    (assign, "$magic_will_choose", magic_Sandstorm),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Sandstorm,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Sandstorm),
                  (try_end),
                (try_end),
              (else_try),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Teleport),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Sandstorm,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Sandstorm,magic_Learned),
                    (assign, "$magic_will_choose", magic_Sandstorm),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Sandstorm,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Sandstorm),
                  (try_end),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (assign, "$magic_will_choose", magic_Teleport),
                (try_end),
              (else_try),
                  (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Sandstorm),
                  (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Sandstorm),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Teleport,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos1"),
                  (assign, "$magic_will_choose", magic_Teleport),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Sandstorm,magic_Learned),
                    (assign, "$magic_will_choose", magic_Sandstorm),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Sandstorm,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Sandstorm),
                  (try_end),
                (try_end),
              (else_try),
                (try_begin),
                  (troop_slot_ge,"trp_player",slot_troop_Teleport,magic_Novice),
                  (overlay_animate_to_position, "$magic_choose", 500, "$pos1"),
                  (assign, "$magic_will_choose", magic_Teleport),
                (else_try),
                  (overlay_animate_to_position, "$magic_choose", 200, "$pos2"),
                  (try_begin),
                    (troop_slot_eq,"trp_player",slot_troop_Sandstorm,magic_Learned),
                    (assign, "$magic_will_choose", magic_Sandstorm),
                  (else_try),
                    (troop_slot_eq,"trp_player",slot_troop_Sandstorm,magic_Master),
                    (assign, "$magic_will_choose", magic_Master_Sandstorm),
                  (try_end),
                (try_end),
              (try_end),
            (try_end),
    ]),
   ("choose_spells_begin",
[       (position_set_x,pos1,120),
        (position_set_y,pos1,120),
        (overlay_set_position, "$magic_choose", pos1),
        (overlay_set_alpha, "$magic_choose", 0xff),
        (position_set_x,pos2,200),
        (position_set_y,pos2,120),
        (position_set_x,pos3,280),
        (position_set_y,pos3,120),
        (position_set_x,pos4,360),
        (position_set_y,pos4,120),
        (position_set_x,pos5,440),
        (position_set_y,pos5,120),
        (position_set_x,pos6,520),
        (position_set_y,pos6,120),
        (assign,":spells_num",0),
    (try_begin),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Type,magic_fire_skills),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Fireball,magic_Novice),
          (assign,":pos",pos1),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon1", ":pos"),
          (assign,"$pos1",":pos"),
          (overlay_set_alpha, "$magic_icon1", 0xff),
          (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Fireball),
          (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Searing_Ray),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Searing_Ray,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon2", ":pos"),
          (assign,"$pos2",":pos"),
          (overlay_set_alpha, "$magic_icon2", 0xff),
          (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Searing_Ray),
          (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Burning_Trail),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Burning_Trail,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (eq,":spells_num",2),
        (assign,":pos",pos3),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon3", ":pos"),
          (assign,"$pos3",":pos"),
          (overlay_set_alpha, "$magic_icon3", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Burning_Trail),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Wall_of_Fire,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (eq,":spells_num",2),
        (assign,":pos",pos3),
      (else_try),
        (eq,":spells_num",3),
        (assign,":pos",pos4),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon4", ":pos"),
          (assign,"$pos4",":pos"),
          (overlay_set_alpha, "$magic_icon4", 0xff),
          (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Wall_of_Fire),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Wall_of_Fire),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Fire_Shroud,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (eq,":spells_num",2),
        (assign,":pos",pos3),
      (else_try),
        (eq,":spells_num",3),
        (assign,":pos",pos4),
      (else_try),
        (eq,":spells_num",4),
        (assign,":pos",pos5),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon5", ":pos"),
          (assign,"$pos5",":pos"),
          (overlay_set_alpha, "$magic_icon5", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Fire_Shroud),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
           (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_no_magic),
        (try_begin),
          (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Novice),
          (assign, "$magic_will_choose", magic_Novice_Fireball),
        (else_try),
          (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Journeyman),
          (assign, "$magic_will_choose", magic_Journeyman_Fireball),
        (else_try),
          (troop_slot_eq,"trp_player",slot_troop_Fireball,magic_Master),
          (assign, "$magic_will_choose", magic_Master_Fireball),
        (try_end),
      (try_end),
    (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Type,magic_cold_skills),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Wave,magic_Novice),
          (assign,":pos",pos1),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon6", ":pos"),
          (assign,"$pos1",":pos"),
          (overlay_set_alpha, "$magic_icon6", 0xff),
          (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Wave),
          (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Freezing_Trail),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Freezing_Trail,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon7", ":pos"),
          (assign,"$pos2",":pos"),
          (overlay_set_alpha, "$magic_icon7", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Freezing_Trail),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Ice_Storm,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (eq,":spells_num",2),
        (assign,":pos",pos3),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon8", ":pos"),
          (assign,"$pos3",":pos"),
          (overlay_set_alpha, "$magic_icon8", 0xff),
          (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Ice_Storm),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Ice_Storm),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Tsunami,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (eq,":spells_num",2),
        (assign,":pos",pos3),
      (else_try),
        (eq,":spells_num",3),
        (assign,":pos",pos4),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon9", ":pos"),
          (assign,"$pos4",":pos"),
          (overlay_set_alpha, "$magic_icon9", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Tsunami),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
           (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_no_magic),
        (try_begin),
          (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Novice),
          (assign, "$magic_will_choose", magic_Novice_Wave),
        (else_try),
          (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Journeyman),
          (assign, "$magic_will_choose", magic_Journeyman_Wave),
        (else_try),
          (troop_slot_eq,"trp_player",slot_troop_Wave,magic_Master),
          (assign, "$magic_will_choose", magic_Master_Wave),
        (try_end),
      (try_end),
    (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Type,magic_auxiliary_spells),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Cure,magic_Novice),
          (assign,":pos",pos1),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon10", ":pos"),
          (assign,"$pos1",":pos"),
          (overlay_set_alpha, "$magic_icon10", 0xff),
          (troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Novice_Cure),
          (neg|troop_slot_ge,"trp_player",slot_troop_Magic_Choose,magic_Cats_grace),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Ammunition_Restoration,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon14", ":pos"),
          (assign,"$pos2",":pos"),
          (overlay_set_alpha, "$magic_icon14", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Ammunition_Restoration),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Cats_grace,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (eq,":spells_num",2),
        (assign,":pos",pos3),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon11", ":pos"),
          (assign,"$pos3",":pos"),
          (overlay_set_alpha, "$magic_icon11", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Cats_grace),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Bulls_strength,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (eq,":spells_num",2),
        (assign,":pos",pos3),
      (else_try),
        (eq,":spells_num",3),
        (assign,":pos",pos4),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon12", ":pos"),
          (assign,"$pos4",":pos"),
          (overlay_set_alpha, "$magic_icon12", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Bulls_strength),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Mass_Cure,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (eq,":spells_num",2),
        (assign,":pos",pos3),
      (else_try),
        (eq,":spells_num",3),
        (assign,":pos",pos4),
      (else_try),
        (eq,":spells_num",4),
        (assign,":pos",pos5),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon13", ":pos"),
          (assign,"$pos5",":pos"),
          (overlay_set_alpha, "$magic_icon13", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Mass_Cure),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Mind_Fog,magic_Learned),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (eq,":spells_num",2),
        (assign,":pos",pos3),
      (else_try),
        (eq,":spells_num",3),
        (assign,":pos",pos4),
      (else_try),
        (eq,":spells_num",4),
        (assign,":pos",pos5),
      (else_try),
        (eq,":spells_num",5),
        (assign,":pos",pos6),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon18", ":pos"),
          (assign,"$pos6",":pos"),
          (overlay_set_alpha, "$magic_icon18", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Mind_Fog),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
           (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_no_magic),
        (try_begin),
          (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Novice),
          (assign, "$magic_will_choose", magic_Novice_Cure),
        (else_try),
          (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Journeyman),
          (assign, "$magic_will_choose", magic_Journeyman_Cure),
        (else_try),
          (troop_slot_eq,"trp_player",slot_troop_Cure,magic_Master),
          (assign, "$magic_will_choose", magic_Master_Cure),
        (try_end),
      (try_end),
    (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Type,magic_awaken_skills),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Summon_Undead,magic_Novice),
          (assign,":pos",pos1),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon15", ":pos"),
          (assign,"$pos1",":pos"),
          (overlay_set_alpha, "$magic_icon15", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Summon_Undead),
          (overlay_set_position, "$magic_choose", ":pos"),
          (assign, "$magic_will_choose", magic_Summon_Undead),
      (try_end),
      (try_begin),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_no_magic),
          (troop_slot_ge,"trp_player",slot_troop_Summon_Undead,magic_Novice),
          (assign, "$magic_will_choose", magic_Summon_Undead),
      (try_end),
    (else_try),
        (troop_slot_eq,"trp_player",slot_troop_Magic_Type,magic_other_skills),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Teleport,magic_Novice),
          (assign,":pos",pos1),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon16", ":pos"),
          (assign,"$pos1",":pos"),
          (overlay_set_alpha, "$magic_icon16", 0xff),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Teleport),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
          (troop_slot_ge,"trp_player",slot_troop_Sandstorm,magic_Novice),
      (try_begin),
        (eq,":spells_num",1),
        (assign,":pos",pos2),
      (else_try),
        (assign,":pos",pos1),
      (try_end),
          (val_add,":spells_num",1),
          (overlay_set_position, "$magic_icon17", ":pos"),
          (assign,"$pos2",":pos"),
          (overlay_set_alpha, "$magic_icon17", 0xff),
          (this_or_next|troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Sandstorm),
          (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_Master_Sandstorm),
          (overlay_set_position, "$magic_choose", ":pos"),
      (try_end),
      (try_begin),
           (troop_slot_eq,"trp_player",slot_troop_Magic_Choose,magic_no_magic),
          (troop_slot_ge,"trp_player",slot_troop_Teleport,magic_Novice),
          (assign, "$magic_will_choose", magic_Teleport),
      (try_end),
    (try_end),
        (assign, "$choose_magic_begin",0),
    ]),
